/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#pragma once

#include "velox/connectors/Connector.h"
#include "velox/core/ITypedExpr.h"
#include "velox/type/Filter.h"
#include "velox/type/Subfield.h"
#include "velox/type/Type.h"

namespace facebook::velox::connector::hive {

class HiveColumnHandle : public ColumnHandle {
 public:
  /// NOTE: Make sure to update the mapping in columnTypeNames() when modifying
  /// this.
  enum class ColumnType {
    kPartitionKey,
    kRegular,
    kSynthesized,
    /// A zero-based row number of type BIGINT auto-generated by the connector.
    /// Rows numbers are unique within a single file only.
    kRowIndex,
    kRowId,
  };

  struct ColumnParseParameters {
    enum PartitionDateValueFormat {
      kISO8601,
      kDaysSinceEpoch,
    } partitionDateValueFormat;
  };

  /// NOTE: 'dataType' is the column type in target write table. 'hiveType' is
  /// converted type of the corresponding column in source table which might not
  /// be the same type, and the table scan needs to do data coercion if needs.
  /// The table writer also needs to respect the type difference when processing
  /// input data such as bucket id calculation.
  HiveColumnHandle(
      const std::string& name,
      ColumnType columnType,
      TypePtr dataType,
      TypePtr hiveType,
      std::vector<common::Subfield> requiredSubfields = {},
      ColumnParseParameters columnParseParameters = {},
      std::function<void(VectorPtr&)> postProcessor = {})
      : name_(name),
        columnType_(columnType),
        dataType_(std::move(dataType)),
        hiveType_(std::move(hiveType)),
        requiredSubfields_(std::move(requiredSubfields)),
        columnParseParameters_(columnParseParameters),
        postProcessor_(std::move(postProcessor)) {
    VELOX_USER_CHECK(
        dataType_->equivalent(*hiveType_),
        "data type {} and hive type {} do not match",
        dataType_->toString(),
        hiveType_->toString());
  }

  const std::string& name() const override {
    return name_;
  }

  ColumnType columnType() const {
    return columnType_;
  }

  const TypePtr& dataType() const {
    return dataType_;
  }

  const TypePtr& hiveType() const {
    return hiveType_;
  }

  /// Applies to columns of complex types: arrays, maps and structs.  When a
  /// query uses only some of the subfields, the engine provides the complete
  /// list of required subfields and the connector is free to prune the rest.
  ///
  /// Examples:
  ///  - SELECT a[1], b['x'], x.y FROM t
  ///  - SELECT a FROM t WHERE b['y'] > 10
  ///
  /// Pruning a struct means populating some of the members with null values.
  ///
  /// Pruning a map means dropping keys not listed in the required subfields.
  ///
  /// Pruning arrays means dropping values with indices larger than maximum
  /// required index.
  const std::vector<common::Subfield>& requiredSubfields() const {
    return requiredSubfields_;
  }

  bool isPartitionKey() const {
    return columnType_ == ColumnType::kPartitionKey;
  }

  bool isPartitionDateValueDaysSinceEpoch() const {
    return columnParseParameters_.partitionDateValueFormat ==
        ColumnParseParameters::kDaysSinceEpoch;
  }

  /// Apply some row-wise post processing to this column when it is present in
  /// output.
  ///
  /// It's not allowed to change the size of the vector in the processor.  The
  /// top level vector is guaranteed to be safe to change.  Any inner vectors
  /// and buffers need to check the reference count before doing any change in
  /// place, otherwise you need to allocate new vectors and buffers.
  ///
  /// For lazy vector, this will be applied after the lazy vector is loaded.
  /// This is only applied after all the filtering is done; the filters (both
  /// subfield filters and remaining filter) still apply to values before post
  /// processing.  ValueHook usage will be disabled if a post processor is
  /// present.
  const std::function<void(VectorPtr&)>& postProcessor() const {
    return postProcessor_;
  }

  std::string toString() const override;

  folly::dynamic serialize() const override;

  static ColumnHandlePtr create(const folly::dynamic& obj);

  static std::string columnTypeName(HiveColumnHandle::ColumnType columnType);

  static HiveColumnHandle::ColumnType columnTypeFromName(
      const std::string& name);

  static void registerSerDe();

 private:
  const std::string name_;
  const ColumnType columnType_;
  const TypePtr dataType_;
  const TypePtr hiveType_;
  const std::vector<common::Subfield> requiredSubfields_;
  const ColumnParseParameters columnParseParameters_;
  const std::function<void(VectorPtr&)> postProcessor_;
};

using HiveColumnHandlePtr = std::shared_ptr<const HiveColumnHandle>;
using HiveColumnHandleMap =
    std::unordered_map<std::string, HiveColumnHandlePtr>;

class HiveTableHandle : public ConnectorTableHandle {
 public:
  /// @param sampleRate Sampling rate in (0, 1] range. 0.1 means 10% sampling.
  /// 1.0 means no sampling. Default is no sampling.
  HiveTableHandle(
      std::string connectorId,
      const std::string& tableName,
      bool filterPushdownEnabled,
      common::SubfieldFilters subfieldFilters,
      const core::TypedExprPtr& remainingFilter,
      const RowTypePtr& dataColumns = nullptr,
      std::vector<std::string> indexColumns = {},
      const std::unordered_map<std::string, std::string>& tableParameters = {},
      std::vector<HiveColumnHandlePtr> filterColumnHandles = {},
      double sampleRate = 1.0);

  /// Legacy constructor without indexColumns parameter for backward
  /// compatibility.
  HiveTableHandle(
      std::string connectorId,
      const std::string& tableName,
      bool filterPushdownEnabled,
      common::SubfieldFilters subfieldFilters,
      const core::TypedExprPtr& remainingFilter,
      const RowTypePtr& dataColumns,
      const std::unordered_map<std::string, std::string>& tableParameters,
      std::vector<HiveColumnHandlePtr> filterColumnHandles,
      double sampleRate = 1.0);

  const std::string& tableName() const {
    return tableName_;
  }

  const std::string& name() const override {
    return tableName();
  }

  bool supportsIndexLookup() const override {
    return !indexColumns_.empty();
  }

  bool needsIndexSplit() const override {
    return true;
  }

  [[deprecated]] bool isFilterPushdownEnabled() const {
    return filterPushdownEnabled_;
  }

  /// Single field filters that can be applied efficiently during file reading.
  const common::SubfieldFilters& subfieldFilters() const {
    return subfieldFilters_;
  }

  /// Everything else that cannot be converted into subfield filters, but still
  /// require the data source to filter out.  This is usually less efficient
  /// than subfield filters but supports arbitrary boolean expression.
  const core::TypedExprPtr& remainingFilter() const {
    return remainingFilter_;
  }

  /// Sampling rate between 0 and 1 (excluding 0). 0.1 means 10%
  /// sampling. 1.0 means no sampling.
  double sampleRate() const {
    return sampleRate_;
  }

  /// Subset of schema of the table that we store in file (i.e.,
  /// non-partitioning columns).  This must be in the exact order as columns in
  /// file (except trailing columns), but with the table schema during read
  /// time.
  ///
  /// This is needed for multiple purposes, including reading TEXTFILE and
  /// handling schema evolution.
  const RowTypePtr& dataColumns() const {
    return dataColumns_;
  }

  /// Returns the names of the index columns for the table.
  const std::vector<std::string>& indexColumns() const {
    return indexColumns_;
  }

  /// Extra parameters to pass down to file format reader layer.  Keys should be
  /// in dwio::common::TableParameter.
  const std::unordered_map<std::string, std::string>& tableParameters() const {
    return tableParameters_;
  }

  /// Extra columns that are used in filters and remaining filters, but not in
  /// the output.  If there is overlap with data source assignments parameter,
  /// the name and types should be the same (the required subfields are taken
  /// from assignments).
  const std::vector<HiveColumnHandlePtr> filterColumnHandles() const {
    return filterColumnHandles_;
  }

  std::string toString() const override;

  folly::dynamic serialize() const override;

  static ConnectorTableHandlePtr create(
      const folly::dynamic& obj,
      void* context);

  static void registerSerDe();

 private:
  const std::string tableName_;
  const bool filterPushdownEnabled_;
  const common::SubfieldFilters subfieldFilters_;
  const core::TypedExprPtr remainingFilter_;
  const double sampleRate_;
  const RowTypePtr dataColumns_;
  const std::vector<std::string> indexColumns_;
  const std::unordered_map<std::string, std::string> tableParameters_;
  const std::vector<HiveColumnHandlePtr> filterColumnHandles_;
};

using HiveTableHandlePtr = std::shared_ptr<const HiveTableHandle>;

} // namespace facebook::velox::connector::hive

template <>
struct fmt::formatter<
    facebook::velox::connector::hive::HiveColumnHandle::ColumnType>
    : formatter<std::string> {
  auto format(
      facebook::velox::connector::hive::HiveColumnHandle::ColumnType type,
      format_context& ctx) const {
    return formatter<std::string>::format(
        facebook::velox::connector::hive::HiveColumnHandle::columnTypeName(
            type),
        ctx);
  }
};
