/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "velox/experimental/ucx-exchange/Communicator.h"
#include <cuda_runtime.h>
#include <ucxx/api.h>
#include <ucxx/utils/ucx.h>
#include <algorithm>
#include <iostream>
#include "velox/common/base/Exceptions.h"
#include "velox/experimental/cudf/CudfConfig.h"
#include "velox/experimental/ucx-exchange/CommElement.h"
#include "velox/experimental/ucx-exchange/EndpointRef.h"
#include "velox/experimental/ucx-exchange/UcxExchangeModules.h"
#include "velox/experimental/ucx-exchange/UcxExchangeServer.h"
#include "velox/experimental/ucx-exchange/UcxExchangeSource.h"

#include <glog/logging.h>

using namespace facebook::velox::cudf_velox;

namespace facebook::velox::ucx_exchange {

// static
std::once_flag Communicator::onceFlag;
std::shared_ptr<Communicator> Communicator::instancePtr_ = nullptr;

/* static */
std::shared_ptr<Communicator> Communicator::initAndGet(
    uint16_t port,
    std::string_view coordinatorURL,
    ContinueFuture* future) {
  if (!FLAGS_velox_ucx_exchange) {
    return nullptr;
  }
  std::call_once(onceFlag, [&] {
    instancePtr_ = std::shared_ptr<Communicator>(new Communicator());
    instancePtr_->port_ = port;
    instancePtr_->coordinatorURL_ = coordinatorURL;
    // Generate a random unique worker ID for same-process detection.
    // std::random_device reads from /dev/urandom on Linux (non-blocking).
    // A 64-bit random value has negligible collision probability.
    std::random_device rd;
    std::mt19937_64 gen(rd());
    std::uniform_int_distribution<uint64_t> dist;
    instancePtr_->workerId_ = dist(gen);
    LOG(INFO) << "Communicator workerId=" << instancePtr_->workerId_;
    auto logLevel = CudfConfig::getInstance().exchangeLogLevel;
    LOG(INFO) << "ucx-exchange VLOG level set to " << logLevel;
    if (logLevel > 0) {
      // Set VLOG level for all ucx-exchange source files.
      // kUcxExchangeModules is auto-generated by CMake from the source list.
      for (const char* module : kUcxExchangeModules) {
        google::SetVLOGLevel(module, logLevel);
      }
    }
    if (future) {
      *future = instancePtr_->promise_.getSemiFuture();
    }
  });
  VELOX_CHECK_EQ(
      instancePtr_->port_,
      port,
      "Cannot initialize communicator again with different port");
  return instancePtr_;
}

/* static */
std::shared_ptr<Communicator> Communicator::getInstance() {
  VELOX_CHECK_NOT_NULL(
      instancePtr_, "Communicator not initialized. Call init(port) first.");
  return instancePtr_;
}

/* static */ void Communicator::cStyleListenerCallback(
    ucp_conn_request_h conn_request,
    void* arg) {
  // cast the argument back to our instance variable:
  Communicator* instance = static_cast<Communicator*>(arg);
  instance->listenerCallback(conn_request);
}

Communicator::~Communicator() {
  listener_.reset();
  // Note: worker_->flush() was removed - it only applies to RMA (Remote Memory
  // Access) operations like ucp_put/ucp_get, which this code doesn't use.
  // This code only uses tag send/recv and active messages.
  worker_->progressWorkerEvent(100);
  worker_.reset();
  context_.reset();
  VLOG(3) << "Communicator destructed";
}

/// @brief Run doesn't return until stop() is called.
/// All operations of the communicator will be carried out in the thread
/// that calls run.
void Communicator::run() {
  VLOG(3) << "Using error handling mode: "
          << CudfConfig::getInstance().ucxxErrorHandling << std::endl;
  VLOG(3) << "Using blocking progress mode: "
          << CudfConfig::getInstance().ucxxBlockingPolling << std::endl;

  running_.store(true);
  // Force CUDA context creation.
  auto cudaStatus = cudaFree(0);
  VELOX_CHECK(
      cudaStatus == cudaSuccess,
      "Failed to initialize CUDA context: {}",
      cudaGetErrorString(cudaStatus));

  // create the UCXX context, worker, listener-context etc.
  if (CudfConfig::getInstance().ucxxBlockingPolling) {
    context_ = ucxx::createContext({}, ucxx::Context::defaultFeatureFlags);
  } else {
    context_ = ucxx::createContext({}, UCP_FEATURE_TAG | UCP_FEATURE_AM);
  }

  worker_ = context_->createWorker();

  if (CudfConfig::getInstance().ucxxBlockingPolling) {
    // Communicator is using blocking progress mode.
    worker_->initBlockingProgressMode();
  }

  listener_ = worker_->createListener(
      port_, Communicator::cStyleListenerCallback, this);

  // Setup the active message callback that handles the
  // initial handshake and creates the senders.
  ucxx::AmReceiverCallbackInfo info(kAmCallbackOwner, kAmCallbackId);
  worker_->registerAmReceiverCallback(info, &Acceptor::cStyleAMCallback);

  promise_.setValue();

  VLOG(3) << "Communicator running.";
  const bool blockingMode = CudfConfig::getInstance().ucxxBlockingPolling;
  while (running_) {
    try {
      // Periodic heartbeat for diagnostic logging.
      auto now = std::chrono::steady_clock::now();
      if (now - lastHeartbeat_ >= std::chrono::seconds(5)) {
        std::lock_guard<std::mutex> lock(elemMutex_);

        // GPU memory usage via CUDA runtime.
        size_t gpuFree = 0, gpuTotal = 0;
        auto memStatus = cudaMemGetInfo(&gpuFree, &gpuTotal);
        if (memStatus != cudaSuccess) {
          LOG(WARNING) << "cudaMemGetInfo failed: "
                       << cudaGetErrorString(memStatus);
        }
        size_t gpuUsedMB = (gpuTotal - gpuFree) / (1024 * 1024);
        size_t gpuFreeMB = gpuFree / (1024 * 1024);
        size_t gpuTotalMB = gpuTotal / (1024 * 1024);

        // Count ExSrv vs ExSrc elements.
        int numServers = 0, numSources = 0;
        for (const auto& elem : elements_) {
          if (dynamic_cast<UcxExchangeServer*>(elem.get())) {
            ++numServers;
          } else if (dynamic_cast<UcxExchangeSource*>(elem.get())) {
            ++numSources;
          }
        }

        size_t numEndpoints;
        {
          std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
          numEndpoints = endpoints_.size();
        }
        VLOG(2) << "[COMM-HEARTBEAT] workQueue=" << workQueue_.size()
                << " elements=" << elements_.size()
                << " (servers=" << numServers << " sources=" << numSources
                << ")"
                << " endpoints=" << numEndpoints
                << " deferredCleanup=" << deferredEndpointCleanup_.size()
                << " deferredRequests=" << deferredRequests_.size()
                << " workItemsProcessed=" << workItemsProcessed_
                << " GPU=" << gpuUsedMB << "/" << gpuTotalMB << "MB"
                << " (free=" << gpuFreeMB << "MB)";
        workItemsProcessed_ = 0;
        lastHeartbeat_ = now;
      }

      // Process deferred endpoint cleanups from callbacks.
      // UCX callbacks cannot call closeBlocking() (which progresses the
      // worker) or iterate communicators_, so they defer cleanup to
      // this main loop via deferEndpointCleanup().
      while (auto ep = deferredEndpointCleanup_.pop()) {
        VLOG(3) << "Processing deferred endpoint cleanup";
        // First, close all communicators associated with this endpoint.
        // This must happen before removeEndpointRef() which may destroy
        // the endpoint.
        ep->closeAndDrainCommunicators();
        removeEndpointRef(ep);
      }

      // Process the work queue. Make sure that communication is progressed
      // after each call to a comms element, otherwise we will deadlock.
      while (auto comms = workQueue_.pop()) {
        comms->process();
        ++workItemsProcessed_;
        // Progress after each work item to allow UCXX to advance
        // its internal state (complete sends/receives, fire callbacks).
        // Use non-blocking progress here to avoid blocking between
        // work items -- we want to drain the queue promptly.
        worker_->progress();
      }

      // Clean up deferred requests that UCX has fully processed.
      // These are cancelled requests whose GPU buffers needed to stay
      // alive until UCX finished any in-flight operations on them.
      if (!deferredRequests_.empty()) {
        deferredRequests_.erase(
            std::remove_if(
                deferredRequests_.begin(),
                deferredRequests_.end(),
                [](const auto& req) { return req->isCompleted(); }),
            deferredRequests_.end());
      }

      // All queues are drained. Now wait for UCXX network events.
      // In blocking mode, this will block until a UCXX event arrives
      // or worker_->signal() is called (from addToWorkQueue,
      // deferEndpointCleanup, or stop).
      if (blockingMode) {
        worker_->progressWorkerEvent(0);
      } else {
        worker_->progress();
      }
    } catch (ucxx::IOError& e) {
      LOG(ERROR) << "In Communicator main loop UCXX Exception: " << e.what();
      throw;
    }
  }
  VLOG(3) << "Communicator stopping.";
}

/// @brief Stops the communicator, called from an outside thread.
void Communicator::stop() {
  running_.store(false);
  signalWorker();
  // Only log fields that are safe to read from an outside thread.
  // endpoints_ is only accessed from the Communicator thread, so reading
  // it here would be a data race.
  VLOG(3) << "In Communicator::stop "
          << " elements_.size(): " << elements_.size()
          << " workQueue_.size(): " << workQueue_.size();
}

void Communicator::registerCommElement(std::shared_ptr<CommElement> comms) {
  std::lock_guard<std::mutex> lock(elemMutex_);
  auto ret = elements_.insert(comms);
  VELOX_CHECK(ret.second, "CommElement already registered!");
  // Also put the comms element into the work queue.
  workQueue_.push(comms);
  signalWorker();
}

void Communicator::signalWorker() {
  if (worker_ && CudfConfig::getInstance().ucxxBlockingPolling) {
    worker_->signal();
  }
}

void Communicator::addToWorkQueue(std::shared_ptr<CommElement> comms) {
  if (!comms) {
    return;
  }
  workQueue_.push(comms);
  signalWorker();
}

void Communicator::unregister(std::shared_ptr<CommElement> comms) {
  std::lock_guard<std::mutex> lock(elemMutex_);
  if (!comms) {
    return;
  }
  workQueue_.erase(comms);
  elements_.erase(comms);
}

std::shared_ptr<EndpointRef> Communicator::assocEndpointRef(
    std::shared_ptr<CommElement> comms,
    HostPort hostPort) {
  std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
  auto it = endpoints_.find(hostPort);
  if (it != endpoints_.end()) {
    std::shared_ptr<EndpointRef> ep = it->second;
    ep->addCommElem(comms);
    return ep;
  }
  // endpoint doesn't exist. Need to connect. Enable error handling.
  auto ep = worker_->createEndpointFromHostname(
      hostPort.hostname,
      hostPort.port,
      CudfConfig::getInstance().ucxxErrorHandling);
  std::shared_ptr<EndpointRef> epRef = nullptr;
  if (ep != nullptr) {
    epRef = std::make_shared<EndpointRef>(ep);
    epRef->addCommElem(comms);
    if (CudfConfig::getInstance().ucxxErrorHandling) {
      ep->setCloseCallback(EndpointRef::onClose, epRef);
    }
    endpoints_.insert(std::pair{hostPort, epRef});
  }
  return epRef;
}

void Communicator::removeEndpointRef(std::shared_ptr<EndpointRef> ep) {
  std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
  VLOG(3) << "In Communicator::removeEndpointRef for Communicator with port = "
          << Communicator::getInstance()->port_;

  // Close the endpoint if it's still alive.
  // NOTE: This calls closeBlocking() which progresses the worker internally,
  // which can fire listenerCallback() re-entrantly — hence the recursive mutex.
  // This method must NOT be called from within a UCX callback.
  // Use deferEndpointCleanup() from callbacks instead.
  if (ep->endpoint_ && ep->endpoint_->isAlive()) {
    VLOG(3) << "In Communicator::removeEndpointRef call closeBlocking";
    ep->endpoint_->closeBlocking();
  }
  for (auto it = endpoints_.begin(); it != endpoints_.end();) {
    if (it->second == ep) {
      it = endpoints_.erase(it);
    } else {
      ++it;
    }
  }
  VLOG(3) << "- Communicator::removeEndpointRef";
}

void Communicator::deferEndpointCleanup(std::shared_ptr<EndpointRef> ep) {
  // This method is safe to call from UCX callbacks because it doesn't
  // call any blocking/progress functions. The actual cleanup happens
  // in the main run() loop.
  VLOG(3) << "Deferring endpoint cleanup to main loop";
  deferredEndpointCleanup_.push(ep);
  signalWorker();
}

void Communicator::deferRequestCleanup(std::shared_ptr<ucxx::Request> request) {
  if (request) {
    deferredRequests_.push_back(std::move(request));
  }
}

std::shared_ptr<EndpointRef> Communicator::findEndpointRefByHandle(
    ucp_ep_h handle) {
  auto it = acceptor_.handleToEndpointRef_.find(handle);
  if (it != acceptor_.handleToEndpointRef_.end()) {
    return it->second;
  }
  return nullptr;
}

const std::string& Communicator::getCoordinatorUrl() {
  return coordinatorURL_;
}

std::string Communicator::getListenerIp() const {
  if (listener_) {
    return listener_->getIp();
  }
  return "";
}

uint16_t Communicator::getListenerPort() const {
  if (listener_) {
    return listener_->getPort();
  }
  return port_;
}

/// @brief The callback method that is invoked when a client connects.
void Communicator::listenerCallback(ucp_conn_request_h conn_request) {
  char ip_str[INET6_ADDRSTRLEN];
  char port_str[INET6_ADDRSTRLEN];
  ucp_conn_request_attr_t attr{};

  attr.field_mask = UCP_CONN_REQUEST_ATTR_FIELD_CLIENT_ADDR;
  ucxx::utils::ucsErrorThrow(ucp_conn_request_query(conn_request, &attr));
  ucxx::utils::sockaddr_get_ip_port_str(
      &attr.client_address, ip_str, port_str, INET6_ADDRSTRLEN);
  VLOG(3)
      << "Communicator received a connection request from client at address "
      << ip_str << ":" << port_str;

  // incoming endpoints are not shared. Outgoing endpoints to the same node are
  // shared. This guarantees that between any two nodes, there will be at most 2
  // endpoints, one per direction. For compatibility reasons, both incoming and
  // outgoing endpoints are represented using the EndpointRef.
  auto endpoint = listener_->createEndpointFromConnRequest(
      conn_request, CudfConfig::getInstance().ucxxErrorHandling);
  // Pass the peer's actual IP to EndpointRef for reliable intra-node detection.
  auto epRef = std::make_shared<EndpointRef>(endpoint, std::string(ip_str));
  if (CudfConfig::getInstance().ucxxErrorHandling) {
    endpoint->setCloseCallback(EndpointRef::onClose, epRef);
  }
  // Add this endpoint reference to the list of endpoints.
  // NOTE: This runs inside a UCX listener callback (during worker progress),
  // so we must not throw — throwing from a UCX callback is undefined behavior.
  unsigned long val = std::strtoul(port_str, nullptr, 10);
  if (val > static_cast<unsigned long>(std::numeric_limits<uint16_t>::max())) {
    LOG(ERROR) << "listenerCallback: port out of range for uint16_t: " << val;
    return;
  }

  uint16_t port = static_cast<uint16_t>(val);
  HostPort hp(ip_str, port);
  {
    std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
    auto res = endpoints_.insert(std::pair{hp, epRef});
    if (!res.second) {
      LOG(ERROR) << "listenerCallback: endpoint already exists for " << ip_str
                 << ":" << port;
      return;
    }
  }
  acceptor_.registerEndpointRef(epRef);
}

} // namespace facebook::velox::ucx_exchange
