if(APPLE)
    set (OPENSSL_INCLUDE_PATHS "/usr/local/opt/openssl@1.1/include")
    set (OPENSSL_PATHS "/usr/local/opt/openssl@1.1/lib")
elseif(UNIX)
    set (OPENSSL_INCLUDE_PATHS "/usr/include")
    set (OPENSSL_PATHS "/usr/lib/x86_64-linux-gnu/")
    #can also try find_package(OpenSSL)
endif()
find_path (OPENSSL_INCLUDE_DIR NAMES openssl/ssl.h PATHS ${OPENSSL_INCLUDE_PATHS})
find_library (OPENSSL_SSL_LIBRARY libssl ssl PATHS ${OPENSSL_PATHS})
find_library (OPENSSL_CRYPTO_LIBRARY libcrypto crypto PATHS ${OPENSSL_PATHS})
set (OPENSSL_LIBRARIES ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
