# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2.1

# This allows us to use CircleCI's dynamic configuration feature
setup: true


# Path-filtering orb is required to continue a pipeline based on
# the path of an updated fileset
orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  version: 2

  path-filtering-workflow:
    jobs:

      - path-filtering/filter:
          name: check-sensitive-paths

          # Format is: <regex path-to-test> <parameter-to-set> <value-of-pipeline-parameter>
          # Regex below will filter out paths with test in them.
          mapping: |
            velox/expression/((?!.*test).*).*  run-longer-expression-fuzzer true
            velox/exec/((?!.*test).*).*  run-longer-expression-fuzzer true
            velox/common/((?!.*test).*).*  run-longer-expression-fuzzer true
            velox/core/((?!.*test).*).* run-longer-expression-fuzzer true
            velox/vector/((?!.*test).*).* run-longer-expression-fuzzer true

          config-path: .circleci/dist_compile.yml
