/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace facebook::velox::wave {
bool registerHeader(const char* text);
const char* velox_experimental_torchwave_KernelParams_h =
    "velox/experimental/torchwave/KernelParams.h\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cstdint>\n"
    "\n"
    "namespace torch::wave {\n"
    "/// Header for host to torch::wave kernel communication. Includeed in both host\n"
    "/// and device code.\n"
    "\n"
    "struct Tensor {\n"
    "  void* storage;\n"
    "  int8_t rank;\n"
    "  int32_t dims[3];\n"
    "  int32_t strides[3];\n"
    "};\n"
    "\n"
    "/// Struct for returning errors to host. Each block has one. These may be\n"
    "/// checked at a delay, so return status that requires action on host side must\n"
    "/// be sent in returnStatus, not here.\n"
    "struct DebugInfo {\n"
    "  int32_t code;\n"
    "  int32_t line;\n"
    "  char message[80];\n"
    "  int64_t extra[2];\n"
    "};\n"
    "\n"
    "/// Each TB fetches its instructions from BlockInfo at blockIdx.x. Copied at\n"
    "/// offset 0 in dynamic shared memory of the block.\n"
    "struct BlockInfo {\n"
    "  /// kernel dependent op code for this block.\n"
    "  int32_t op;\n"
    "\n"
    "  /// Index of this block within the blocks with for the same op.\n"
    "  int32_t blockInOp;\n"
    "\n"
    "  /// Number of blocks for this op.\n"
    "  int32_t numBlocksInOp;\n"
    "\n"
    "  /// Number of data items to process in this block. Suppose 2 blocks of 256\n"
    "  /// with 600 elements to process, the first would have 512 and the next would\n"
    "  /// have 88.\n"
    "  int32_t rowsForBlock;\n"
    "\n"
    "  /// Index of row processed by lane 0 of this block. The block increments this\n"
    "  /// by blockDim.x on each iteration until this is >= rowsForBlock.\n"
    "  int32_t rowIdx{0};\n"
    "  /// Pointer to per-op params, format depends on 'op'.\n"
    "  void* params;\n"
    "\n"
    "  // Pointer to per block return status. If not nullptr, the block must write a\n"
    "  // per-block status to pass to host here. For example, for stream compaction,\n"
    "  // the result length for data processed by this block. Consolidated with\n"
    "  // return data of other blocks for single D to H transfer.\n"
    "  void* returnData;\n"
    "\n"
    "  DebugInfo* debug;\n"
    "};\n"
    "\n"
    "struct TorchWaveParams {\n"
    "  // Pointer to BlockInfo for blockIdx.x 0. gridDim.x consecutive BlockInfos. If\n"
    "  // nullptr the BlockInfos are in inlineInfo.\n"
    "  BlockInfo* info;\n"
    "  BlockInfo inlineInfo[100];\n"
    "};\n"
    "\n"
    "} // namespace torch::wave\n";
bool velox_experimental_torchwave_KernelParams_h_reg =
    registerHeader(velox_experimental_torchwave_KernelParams_h);
const char* velox_experimental_torchwave_Core_cuh =
    "velox/experimental/torchwave/Core.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#include <stdint.h>\n"
    "#include \"velox/experimental/torchwave/KernelParams.h\"\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T* param(const BlockInfo& block, int32_t offset) {\n"
    "  return reinterpret_cast<T*>(reinterpret_cast<char*>(block.params) + offset);\n"
    "}\n"
    "\n"
    "__device__ uint32_t numEl(const Tensor& tensor) {\n"
    "  uint32_t size = 1;\n"
    "  for (auto i = 0; i < tensor.rank; ++i) {\n"
    "    size = size * tensor.dims[i];\n"
    "  }\n"
    "  return size;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ T* storage(const Tensor* tensor) {\n"
    "  return reinterpret_cast<T*>(tensor->storage);\n"
    "}\n"
    "\n"
    "\n"
    "__device__ bool isFastPathTensor(const Tensor& tensor) {\n"
    "  return tensor.rank == 1 && tensor.strides[0] == 1;\n"
    "}\n"
    "\n"
    "#define ENTRY                                                                  \\\n"
    "  __shared__ BlockInfo blockInfo; \\\n"
    "  if (threadIdx.x == 0) {                                                      \\\n"
    "    blockInfo =                                                                \\\n"
    "        params.info ? params.info[blockIdx.x] : params.inlineInfo[blockIdx.x]; \\\n"
    "  }                                                                            \\\n"
    "  __syncthreads();\n"
    "} // namespace torch::wave\n";
bool velox_experimental_torchwave_Core_cuh_reg =
    registerHeader(velox_experimental_torchwave_Core_cuh);
const char* velox_experimental_torchwave_Elementwise_cuh =
    "velox/experimental/torchwave/Elementwise.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cstdint>\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "// Binary arithmetic.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __add(T a1, T a2, T alpha) {\n"
    "  return a1 + a2 * alpha;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __sub(T a1, T a2, T alpha) {\n"
    "  return a1 - a2 * alpha;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __mul(T a1, T a2) {\n"
    "  return a1 * a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __div(T a1, T a2) {\n"
    "  return a1 / a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __remainder(T a1, T a2) {\n"
    "  return a1 % a2;\n"
    "}\n"
    "\n"
    "__device__ inline float __remainder(float a1, float a2) {\n"
    "  return remainderf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __remainder(double a1, double a2) {\n"
    "  return ::remainder(a1, a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __fmod(T a1, T a2) {\n"
    "  return a1 % a2;\n"
    "}\n"
    "\n"
    "__device__ inline float __fmod(float a1, float a2) {\n"
    "  return fmodf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __fmod(double a1, double a2) {\n"
    "  return fmod(a1, a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __pow(T a1, T a2) {\n"
    "  return powf(static_cast<float>(a1), static_cast<float>(a2));\n"
    "}\n"
    "\n"
    "__device__ inline float __pow(float a1, float a2) {\n"
    "  return powf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __pow(double a1, double a2) {\n"
    "  return pow(a1, a2);\n"
    "}\n"
    "\n"
    "// Comparison.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __eq(T a1, T a2) {\n"
    "  return a1 == a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __ne(T a1, T a2) {\n"
    "  return a1 != a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __lt(T a1, T a2) {\n"
    "  return a1 < a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __le(T a1, T a2) {\n"
    "  return a1 <= a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __gt(T a1, T a2) {\n"
    "  return a1 > a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __ge(T a1, T a2) {\n"
    "  return a1 >= a2;\n"
    "}\n"
    "\n"
    "// Bitwise.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_and(T a1, T a2) {\n"
    "  return a1 & a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_or(T a1, T a2) {\n"
    "  return a1 | a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_xor(T a1, T a2) {\n"
    "  return a1 ^ a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_not(T a1) {\n"
    "  return ~a1;\n"
    "}\n"
    "\n"
    "// Logical.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_and(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) && static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_or(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) || static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_xor(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) != static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_not(T a1) {\n"
    "  return !static_cast<bool>(a1);\n"
    "}\n"
    "\n"
    "// Unary math.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __abs(T a1) {\n"
    "  return abs(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __abs(float a1) {\n"
    "  return fabsf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __abs(double a1) {\n"
    "  return fabs(a1);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __neg(T a1) {\n"
    "  return -a1;\n"
    "}\n"
    "\n"
    "__device__ inline float __ceil(float a1) {\n"
    "  return ceilf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __ceil(double a1) {\n"
    "  return ceil(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __floor(float a1) {\n"
    "  return floorf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __floor(double a1) {\n"
    "  return floor(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __round(float a1) {\n"
    "  return roundf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __round(double a1) {\n"
    "  return round(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __trunc(float a1) {\n"
    "  return truncf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __trunc(double a1) {\n"
    "  return trunc(a1);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __sign(T a1) {\n"
    "  return (a1 > T(0)) - (a1 < T(0));\n"
    "}\n"
    "\n"
    "__device__ inline float __sqrt(float a1) {\n"
    "  return sqrtf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sqrt(double a1) {\n"
    "  return sqrt(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __rsqrt(float a1) {\n"
    "  return rsqrtf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __rsqrt(double a1) {\n"
    "  return 1.0 / sqrt(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __reciprocal(float a1) {\n"
    "  return 1.0f / a1;\n"
    "}\n"
    "\n"
    "__device__ inline double __reciprocal(double a1) {\n"
    "  return 1.0 / a1;\n"
    "}\n"
    "\n"
    "__device__ inline float __exp(float a1) {\n"
    "  return expf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __exp(double a1) {\n"
    "  return exp(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log(float a1) {\n"
    "  return logf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log(double a1) {\n"
    "  return log(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log2(float a1) {\n"
    "  return log2f(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log2(double a1) {\n"
    "  return log2(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log10(float a1) {\n"
    "  return log10f(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log10(double a1) {\n"
    "  return log10(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log1p(float a1) {\n"
    "  return log1pf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log1p(double a1) {\n"
    "  return log1p(a1);\n"
    "}\n"
    "\n"
    "// Trigonometric.\n"
    "\n"
    "__device__ inline float __sin(float a1) {\n"
    "  return sinf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sin(double a1) {\n"
    "  return sin(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __cos(float a1) {\n"
    "  return cosf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __cos(double a1) {\n"
    "  return cos(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __tan(float a1) {\n"
    "  return tanf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __tan(double a1) {\n"
    "  return tan(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __asin(float a1) {\n"
    "  return asinf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __asin(double a1) {\n"
    "  return asin(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __acos(float a1) {\n"
    "  return acosf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __acos(double a1) {\n"
    "  return acos(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __atan(float a1) {\n"
    "  return atanf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __atan(double a1) {\n"
    "  return atan(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __atan2(float a1, float a2) {\n"
    "  return atan2f(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __atan2(double a1, double a2) {\n"
    "  return atan2(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline float __sinh(float a1) {\n"
    "  return sinhf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sinh(double a1) {\n"
    "  return sinh(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __cosh(float a1) {\n"
    "  return coshf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __cosh(double a1) {\n"
    "  return cosh(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __tanh(float a1) {\n"
    "  return tanhf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __tanh(double a1) {\n"
    "  return tanh(a1);\n"
    "}\n"
    "\n"
    "// Activation functions.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __relu(T a1) {\n"
    "  return a1 > T(0) ? a1 : T(0);\n"
    "}\n"
    "\n"
    "__device__ inline float __sigmoid(float a1) {\n"
    "  return 1.0f / (1.0f + expf(-a1));\n"
    "}\n"
    "\n"
    "__device__ inline double __sigmoid(double a1) {\n"
    "  return 1.0 / (1.0 + exp(-a1));\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __clamp(T a1, T lo, T hi) {\n"
    "  return a1 < lo ? lo : (a1 > hi ? hi : a1);\n"
    "}\n"
    "\n"
    "// Min/max.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __minimum(T a1, T a2) {\n"
    "  return a1 < a2 ? a1 : a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __maximum(T a1, T a2) {\n"
    "  return a1 > a2 ? a1 : a2;\n"
    "}\n"
    "\n"
    "} // namespace torch::wave\n";
bool velox_experimental_torchwave_Elementwise_cuh_reg =
    registerHeader(velox_experimental_torchwave_Elementwise_cuh);
} // namespace facebook::velox::wave
