/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

namespace facebook::velox::wave {
bool registerHeader(const char* text);
inline constexpr const char* velox_experimental_torchwave_KernelParams_h =
    "velox/experimental/torchwave/KernelParams.h\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cstdint>\n"
    "\n"
    "namespace torch::wave {\n"
    "/// Header for host to torch::wave kernel communication. Included in both host\n"
    "/// and device code.\n"
    "\n"
    "constexpr int kMaxDims = 3;\n"
    "\n"
    "// Fast integer division by multiplication using a precomputed magic number.\n"
    "// Adapted from PyTorch ATen IntDivider. The dividend must be at most\n"
    "// INT32_MAX and the divisor must be in [1, INT32_MAX].\n"
    "struct IntDivider {\n"
    "  unsigned int divisor;\n"
    "  unsigned int m1; // magic multiplier\n"
    "  unsigned int shift;\n"
    "\n"
    "  IntDivider() = default;\n"
    "\n"
    "#ifdef __CUDACC__\n"
    "  /// Computes magic number and shift for fast division by 'd'.\n"
    "  __device__ void init(unsigned int d) {\n"
    "    divisor = d;\n"
    "    for (shift = 0; shift < 32; shift++) {\n"
    "      if ((1U << shift) >= divisor) {\n"
    "        break;\n"
    "      }\n"
    "    }\n"
    "    uint64_t one = 1;\n"
    "    uint64_t magic = ((one << 32) * ((one << shift) - divisor)) / divisor + 1;\n"
    "    m1 = magic;\n"
    "  }\n"
    "\n"
    "  __device__ inline unsigned int div(unsigned int n) const {\n"
    "    unsigned int t = __umulhi(n, m1);\n"
    "    return (t + n) >> shift;\n"
    "  }\n"
    "\n"
    "  __device__ inline unsigned int mod(unsigned int n) const {\n"
    "    return n - div(n) * divisor;\n"
    "  }\n"
    "\n"
    "  __device__ inline void\n"
    "  divmod(unsigned int n, unsigned int& q, unsigned int& r) const {\n"
    "    q = div(n);\n"
    "    r = n - q * divisor;\n"
    "  }\n"
    "#endif\n"
    "};\n"
    "\n"
    "/// Device-side tensor descriptor passed in kernel parameters. Shared between\n"
    "/// host and device.\n"
    "struct Tensor {\n"
    "  static constexpr uint32_t kUninited = 0;\n"
    "  static constexpr uint32_t kIniting = 1;\n"
    "  static constexpr uint32_t kInited = 2;\n"
    "\n"
    "  void* storage{nullptr};\n"
    "  int8_t rank{0};\n"
    "  uint8_t elementSize{0};\n"
    "  uint8_t elementType{0};\n"
    "  int32_t dims[kMaxDims]{};\n"
    "  int32_t strides[kMaxDims]{};\n"
    "  uint32_t numEl{0};\n"
    "  uint32_t status{kUninited};\n"
    "  bool contiguous{false};\n"
    "\n"
    "  /// Index calculator dividers, initialized on device via\n"
    "  /// initIndexCalculator().\n"
    "  IntDivider sizes[kMaxDims]{};\n"
    "\n"
    "#ifdef __CUDACC__\n"
    "  /// Initializes IntDivider magic numbers. If 'output' is provided, uses\n"
    "  /// output dims for broadcast index decomposition while keeping this\n"
    "  /// tensor's strides.\n"
    "  // sizes[] are stored innermost-first: sizes[0] = dims[rank-1], etc.\n"
    "  // indexToOffset peels off the innermost dim first via repeated divmod,\n"
    "  // matching row-major linear index decomposition.\n"
    "  __device__ void initIndexCalculator(const Tensor* output = nullptr) {\n"
    "    const int32_t* d = output ? output->dims : dims;\n"
    "    for (int i = 0; i < rank; ++i) {\n"
    "      sizes[i].init(d[rank - 1 - i]);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  /// Returns the byte offset for element 'linearIdx' in this strided tensor.\n"
    "  __device__ inline int32_t indexToOffset(uint32_t linearIdx) const {\n"
    "    int32_t offset = 0;\n"
    "#pragma unroll\n"
    "    for (int dim = 0; dim < kMaxDims; ++dim) {\n"
    "      if (dim == rank) {\n"
    "        break;\n"
    "      }\n"
    "      unsigned int q, r;\n"
    "      sizes[dim].divmod(linearIdx, q, r);\n"
    "      linearIdx = q;\n"
    "      offset += r * strides[rank - 1 - dim];\n"
    "    }\n"
    "    return offset;\n"
    "  }\n"
    "\n"
    "  /// Checks if tensor is contiguous in row-major order (fastest dim at rank-1).\n"
    "  __device__ bool isContiguous() const {\n"
    "    if (rank == 0) {\n"
    "      return true;\n"
    "    }\n"
    "    if (strides[rank - 1] != 1) {\n"
    "      return false;\n"
    "    }\n"
    "    for (int i = rank - 2; i >= 0; --i) {\n"
    "      if (strides[i] != strides[i + 1] * dims[i + 1]) {\n"
    "        return false;\n"
    "      }\n"
    "    }\n"
    "    return true;\n"
    "  }\n"
    "\n"
    "  /// Ensures exactly one thread executes 'func', others wait until complete.\n"
    "  template <typename Func>\n"
    "  __device__ void synchronized(Func func) {\n"
    "    if (atomicAdd(&status, 0u) == kInited) {\n"
    "      return;\n"
    "    }\n"
    "    uint32_t old = atomicCAS(&status, kUninited, kIniting);\n"
    "    if (old != kUninited) {\n"
    "      unsigned int waitNano = 50;\n"
    "      while (atomicAdd(&status, 0u) != kInited) {\n"
    "        __nanosleep(waitNano);\n"
    "        waitNano += threadIdx.x & 31;\n"
    "      }\n"
    "      return;\n"
    "    }\n"
    "    func();\n"
    "    __threadfence();\n"
    "    atomicExch(&status, kInited);\n"
    "  }\n"
    "\n"
    "  /// Initializes contiguity flag, numEl, and index calculator if needed.\n"
    "  /// If 'output' is non-null, uses output dims for the index calculator\n"
    "  /// (broadcast support) and sets numEl from output dims.\n"
    "  template <bool kConcurrent>\n"
    "  __device__ void init(const Tensor* output = nullptr) {\n"
    "    if ((!output || output->dims[0] == dims[0]) && rank == 1 &&\n"
    "        strides[0] == 1) {\n"
    "      numEl = dims[0];\n"
    "      contiguous = true;\n"
    "      return;\n"
    "    }\n"
    "    auto doInit = [&]() {\n"
    "      contiguous = isContiguous();\n"
    "      initIndexCalculator(output);\n"
    "      uint32_t n = 1;\n"
    "      for (int i = 0; i < rank; ++i) {\n"
    "        n *= dims[i];\n"
    "      }\n"
    "      numEl = n;\n"
    "    };\n"
    "    if constexpr (kConcurrent) {\n"
    "      synchronized(doInit);\n"
    "    } else {\n"
    "      if (status == kInited) {\n"
    "        return;\n"
    "      }\n"
    "      doInit();\n"
    "      status = kInited;\n"
    "    }\n"
    "  }\n"
    "#endif\n"
    "};\n"
    "\n"
    "/// Device-side list-of-tensors descriptor for kernel parameters.\n"
    "struct TensorList {\n"
    "  int64_t size;\n"
    "  Tensor** tensors;\n"
    "};\n"
    "\n"
    "/// Device-side list-of-scalars descriptor for kernel parameters.\n"
    "struct ScalarList {\n"
    "  int64_t size;\n"
    "  int64_t* data;\n"
    "};\n"
    "\n"
    "/// Struct for returning errors to host. Each block has one. These may be\n"
    "/// checked at a delay, so return status that requires action on host side must\n"
    "/// be sent in returnStatus, not here.\n"
    "struct DebugInfo {\n"
    "  int64_t clocks{0};\n"
    "  int64_t barrierClocks{0};\n"
    "  int32_t op{0};\n"
    "  int32_t line{0};\n"
    "  int64_t extra[2] = {};\n"
    "  char message[20] = {};\n"
    "};\n"
    "\n"
    "/// Each TB fetches its instructions from BlockInfo at blockIdx.x. Copied at\n"
    "/// offset 0 in dynamic shared memory of the block.\n"
    "struct BlockInfo {\n"
    "  /// kernel dependent op code for this block.\n"
    "  int32_t op;\n"
    "\n"
    "  /// Index of this block within the blocks with for the same op.\n"
    "  int32_t blockInOp;\n"
    "\n"
    "  /// Number of blocks for this op.\n"
    "  int32_t numBlocksInOp;\n"
    "\n"
    "  /// Pointer to per-op params, format depends on 'op'.\n"
    "  void* params;\n"
    "\n"
    "  DebugInfo* debugInfo;\n"
    "\n"
    "  /// clock64() at start of block.\n"
    "  int64_t start;\n"
    "  int64_t barrierClocks;\n"
    "};\n"
    "\n"
    "/// Top-level kernel parameter struct containing BlockInfo array and debug\n"
    "/// pointers.\n"
    "struct TorchWaveParams {\n"
    "  /// Pointer to BlockInfo for blockIdx.x 0. gridDim.x consecutive BlockInfos.\n"
    "  /// If nullptr the BlockInfos are in inlineInfo.\n"
    "  BlockInfo* info;\n"
    "  DebugInfo* debugInfo;\n"
    "  /// If the grid fits in kMaxInlineBlocks BlockInfos, they are inlined here\n"
    "  /// to avoid a separate device allocation for the block info array.\n"
    "  static constexpr int32_t kMaxInlineBlocks = 100;\n"
    "  BlockInfo inlineInfo[kMaxInlineBlocks];\n"
    "};\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_KernelParams_h_reg =
    registerHeader(velox_experimental_torchwave_KernelParams_h);
inline constexpr const char* velox_experimental_torchwave_Core_cuh =
    "velox/experimental/torchwave/Core.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cuda_bf16.h>\n"
    "#include <cuda_fp16.h>\n"
    "#include <stdint.h>\n"
    "#include \"velox/experimental/torchwave/KernelParams.h\"\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T* param(const BlockInfo& block, int32_t offset) {\n"
    "  return reinterpret_cast<T*>(reinterpret_cast<char*>(block.params) + offset);\n"
    "}\n"
    "\n"
    "__device__ inline uint32_t numEl(const Tensor& tensor) {\n"
    "  uint32_t size = 1;\n"
    "  for (auto i = 0; i < tensor.rank; ++i) {\n"
    "    size = size * tensor.dims[i];\n"
    "  }\n"
    "  return size;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T* storage(const Tensor* tensor) {\n"
    "  return reinterpret_cast<T*>(tensor->storage);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T elementRef(Tensor* t, uint32_t idx, uint32_t size) {\n"
    "  return idx < size ? storage<T>(t)[idx] : T();\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ void __copy(Tensor* source, T* dest, BlockInfo& block) {\n"
    "  auto n = source->numEl;\n"
    "  uint32_t start = block.blockInOp * blockDim.x + threadIdx.x;\n"
    "  uint32_t stride = block.numBlocksInOp * blockDim.x;\n"
    "  if (source->contiguous) {\n"
    "    auto* src = storage<T>(source);\n"
    "    for (uint32_t i = start; i < n; i += stride) {\n"
    "      dest[i] = src[i];\n"
    "    }\n"
    "  } else {\n"
    "    for (uint32_t i = start; i < n; i += stride) {\n"
    "      dest[i] = storage<T>(source)[source->indexToOffset(i)];\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "__device__ inline void copyTensorHead(const Tensor* in, Tensor* out) {\n"
    "  out->storage = in->storage;\n"
    "  out->rank = in->rank;\n"
    "  for (int i = 0; i < kMaxDims; ++i) {\n"
    "    out->dims[i] = in->dims[i];\n"
    "    out->strides[i] = in->strides[i];\n"
    "  }\n"
    "}\n"
    "\n"
    "__device__ inline uint32_t\n"
    "complexIdx(bool fast, const Tensor* t, uint32_t idx) {\n"
    "  if (!fast) {\n"
    "    return t->indexToOffset(idx);\n"
    "  }\n"
    "  return idx;\n"
    "}\n"
    "\n"
    "struct Int32X32 {\n"
    "  uint64_t data[32];\n"
    "  __host__ __device__ operator void*() {\n"
    "    return static_cast<void*>(data);\n"
    "  }\n"
    "  __host__ __device__ operator void*() const {\n"
    "    return const_cast<void*>(static_cast<const void*>(data));\n"
    "  }\n"
    "};\n"
    "\n"
    "// Thread 0 loads BlockInfo from params (inlined in TorchWaveParams or from a\n"
    "// separate device allocation) into shared memory; all threads sync before use.\n"
    "// LEAVE records timing into the per-block DebugInfo.\n"
    "#define ENTRY                                                                  \\\n"
    "  __shared__ BlockInfo blockInfo;                                              \\\n"
    "  if (threadIdx.x == 0) {                                                      \\\n"
    "    blockInfo =                                                                \\\n"
    "        params.info ? params.info[blockIdx.x] : params.inlineInfo[blockIdx.x]; \\\n"
    "    blockInfo.debugInfo =                                                      \\\n"
    "        params.debugInfo ? &params.debugInfo[blockIdx.x] : nullptr;            \\\n"
    "    blockInfo.barrierClocks = 0;                                               \\\n"
    "    if (blockInfo.debugInfo) {                                                 \\\n"
    "      blockInfo.start = clock64();                                             \\\n"
    "      memset(blockInfo.debugInfo, 0, sizeof(DebugInfo));                       \\\n"
    "    }                                                                          \\\n"
    "  }                                                                            \\\n"
    "  __syncthreads();\n"
    "\n"
    "#define LEAVE()                                                   \\\n"
    "  __syncthreads();                                                \\\n"
    "  if (threadIdx.x == 0 && blockInfo.debugInfo) {                  \\\n"
    "    blockInfo.debugInfo->clocks = clock64() - blockInfo.start;    \\\n"
    "    blockInfo.debugInfo->barrierClocks = blockInfo.barrierClocks; \\\n"
    "    blockInfo.debugInfo->op = blockInfo.op;                       \\\n"
    "  }\n"
    "\n"
    "// NVIDIA GPU warp size. All scan/reduce templates assume this value.\n"
    "constexpr int32_t kWarpThreads = 32;\n"
    "\n"
    "template <typename T, typename U>\n"
    "__host__ __device__ constexpr inline T roundUp(T value, U factor) {\n"
    "  return (value + (factor - 1)) / factor * factor;\n"
    "}\n"
    "\n"
    "/// Rounds 'x' up to the next multiple of 'y', where y must be a power of two.\n"
    "template <typename T, typename U>\n"
    "__host__ __device__ constexpr inline T roundUpPwr2(T x, U y) {\n"
    "  return (x + (y - 1)) & ~(y - 1);\n"
    "}\n"
    "\n"
    "__device__ inline void traceTensor(const BlockInfo& block, int32_t offset) {\n"
    "  auto* t = param<Tensor>(block, offset);\n"
    "  printf(\n"
    "      \"offset=%d storage=%p rank=%d dims=[%d,%d,%d] strides=[%d,%d,%d]\\n\",\n"
    "      offset,\n"
    "      t->storage,\n"
    "      t->rank,\n"
    "      t->dims[0],\n"
    "      t->dims[1],\n"
    "      t->dims[2],\n"
    "      t->strides[0],\n"
    "      t->strides[1],\n"
    "      t->strides[2]);\n"
    "}\n"
    "\n"
    "#define TRACE0(__x)         \\\n"
    "  do {                      \\\n"
    "    if (threadIdx.x == 0) { \\\n"
    "      __x;                  \\\n"
    "    }                       \\\n"
    "  } while (0)\n"
    "\n"
    "// Each counter offset must be used at most once per kernel invocation.\n"
    "// The counter is not reset after use, so reusing the same offset would\n"
    "// cause the barrier to pass immediately.\n"
    "__device__ inline void opBarrier(BlockInfo& info, int32_t counterOffset) {\n"
    "  __threadfence();\n"
    "  __syncthreads();\n"
    "  if (threadIdx.x == 0) {\n"
    "    auto barrierStart = clock64();\n"
    "    auto* counter = param<int32_t>(info, counterOffset);\n"
    "    atomicAdd(counter, 1);\n"
    "    volatile int32_t* vc = reinterpret_cast<volatile int32_t*>(counter);\n"
    "    while (*vc < info.numBlocksInOp) {\n"
    "      __nanosleep(100);\n"
    "    }\n"
    "    info.barrierClocks += clock64() - barrierStart;\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_Core_cuh_reg =
    registerHeader(velox_experimental_torchwave_Core_cuh);
inline constexpr const char* velox_experimental_torchwave_Elementwise_cuh =
    "velox/experimental/torchwave/Elementwise.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cstdint>\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "// Casts __half and __nv_bfloat16 to float for arithmetic so that mixed-type\n"
    "// expressions (e.g. int32_t * __half) do not hit ambiguous operator overloads\n"
    "// from cuda_fp16.h / cuda_bf16.h.\n"
    "template <typename T>\n"
    "__device__ inline T arithCast(T x) {\n"
    "  return x;\n"
    "}\n"
    "__device__ inline float arithCast(__half x) {\n"
    "  return __half2float(x);\n"
    "}\n"
    "__device__ inline float arithCast(__nv_bfloat16 x) {\n"
    "  return __bfloat162float(x);\n"
    "}\n"
    "\n"
    "// Binary arithmetic.\n"
    "\n"
    "template <typename T, typename T2, typename TAlpha>\n"
    "__device__ inline T __add(T a1, T2 a2, TAlpha alpha) {\n"
    "  return arithCast(a1) + arithCast(a2) * arithCast(alpha);\n"
    "}\n"
    "\n"
    "template <typename T, typename T2, typename TAlpha>\n"
    "__device__ inline T __sub(T a1, T2 a2, TAlpha alpha) {\n"
    "  return arithCast(a1) - arithCast(a2) * arithCast(alpha);\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline T __mul(T a1, T2 a2) {\n"
    "  return arithCast(a1) * arithCast(a2);\n"
    "}\n"
    "\n"
    "template <>\n"
    "__device__ inline bool __mul<bool, bool>(bool a1, bool a2) {\n"
    "  return a1 & a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline T __div(T a1, T2 a2) {\n"
    "  return arithCast(a1) / arithCast(a2);\n"
    "}\n"
    "\n"
    "// Integer true division matching PyTorch semantics: div(int, int) -> double.\n"
    "__device__ inline double __div(int64_t a1, int64_t a2) {\n"
    "  return static_cast<double>(a1) / static_cast<double>(a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __div(int32_t a1, int32_t a2) {\n"
    "  return static_cast<double>(a1) / static_cast<double>(a2);\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline T __remainder(T a1, T2 a2) {\n"
    "  return a1 % a2;\n"
    "}\n"
    "\n"
    "__device__ inline float __remainder(float a1, float a2) {\n"
    "  return remainderf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __remainder(double a1, double a2) {\n"
    "  return ::remainder(a1, a2);\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline T __fmod(T a1, T2 a2) {\n"
    "  return a1 % a2;\n"
    "}\n"
    "\n"
    "__device__ inline float __fmod(float a1, float a2) {\n"
    "  return fmodf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __fmod(double a1, double a2) {\n"
    "  return fmod(a1, a2);\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline T __pow(T a1, T2 a2) {\n"
    "  return powf(static_cast<float>(a1), static_cast<float>(a2));\n"
    "}\n"
    "\n"
    "__device__ inline float __pow(float a1, float a2) {\n"
    "  return powf(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __pow(double a1, double a2) {\n"
    "  return pow(a1, a2);\n"
    "}\n"
    "\n"
    "// Comparison.\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __eq(T a1, T2 a2) {\n"
    "  return a1 == a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __ne(T a1, T2 a2) {\n"
    "  return a1 != a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __lt(T a1, T2 a2) {\n"
    "  return a1 < a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __le(T a1, T2 a2) {\n"
    "  return a1 <= a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __gt(T a1, T2 a2) {\n"
    "  return a1 > a2;\n"
    "}\n"
    "\n"
    "template <typename T, typename T2 = T>\n"
    "__device__ inline bool __ge(T a1, T2 a2) {\n"
    "  return a1 >= a2;\n"
    "}\n"
    "\n"
    "// Bitwise.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_and(T a1, T a2) {\n"
    "  return a1 & a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_or(T a1, T a2) {\n"
    "  return a1 | a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_xor(T a1, T a2) {\n"
    "  return a1 ^ a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __bitwise_not(T a1) {\n"
    "  return ~a1;\n"
    "}\n"
    "\n"
    "template <>\n"
    "__device__ inline bool __bitwise_not<bool>(bool a1) {\n"
    "  return !a1;\n"
    "}\n"
    "\n"
    "// Logical.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_and(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) && static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_or(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) || static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_xor(T a1, T a2) {\n"
    "  return static_cast<bool>(a1) != static_cast<bool>(a2);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool __logical_not(T a1) {\n"
    "  return !static_cast<bool>(a1);\n"
    "}\n"
    "\n"
    "// Unary math.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __abs(T a1) {\n"
    "  return abs(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __abs(float a1) {\n"
    "  return fabsf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __abs(double a1) {\n"
    "  return fabs(a1);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __neg(T a1) {\n"
    "  return -a1;\n"
    "}\n"
    "\n"
    "__device__ inline float __ceil(float a1) {\n"
    "  return ceilf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __ceil(double a1) {\n"
    "  return ceil(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __floor(float a1) {\n"
    "  return floorf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __floor(double a1) {\n"
    "  return floor(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __round(float a1) {\n"
    "  return roundf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __round(double a1) {\n"
    "  return round(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __trunc(float a1) {\n"
    "  return truncf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __trunc(double a1) {\n"
    "  return trunc(a1);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __sign(T a1) {\n"
    "  return (a1 > T(0)) - (a1 < T(0));\n"
    "}\n"
    "\n"
    "__device__ inline float __sqrt(float a1) {\n"
    "  return sqrtf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sqrt(double a1) {\n"
    "  return sqrt(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __rsqrt(float a1) {\n"
    "  return rsqrtf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __rsqrt(double a1) {\n"
    "  return 1.0 / sqrt(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __reciprocal(float a1) {\n"
    "  return 1.0f / a1;\n"
    "}\n"
    "\n"
    "__device__ inline double __reciprocal(double a1) {\n"
    "  return 1.0 / a1;\n"
    "}\n"
    "\n"
    "__device__ inline float __exp(float a1) {\n"
    "  return expf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __exp(double a1) {\n"
    "  return exp(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log(float a1) {\n"
    "  return logf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log(double a1) {\n"
    "  return log(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log2(float a1) {\n"
    "  return log2f(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log2(double a1) {\n"
    "  return log2(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log10(float a1) {\n"
    "  return log10f(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log10(double a1) {\n"
    "  return log10(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __log1p(float a1) {\n"
    "  return log1pf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __log1p(double a1) {\n"
    "  return log1p(a1);\n"
    "}\n"
    "\n"
    "// Trigonometric.\n"
    "\n"
    "__device__ inline float __sin(float a1) {\n"
    "  return sinf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sin(double a1) {\n"
    "  return sin(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __cos(float a1) {\n"
    "  return cosf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __cos(double a1) {\n"
    "  return cos(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __tan(float a1) {\n"
    "  return tanf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __tan(double a1) {\n"
    "  return tan(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __asin(float a1) {\n"
    "  return asinf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __asin(double a1) {\n"
    "  return asin(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __acos(float a1) {\n"
    "  return acosf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __acos(double a1) {\n"
    "  return acos(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __atan(float a1) {\n"
    "  return atanf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __atan(double a1) {\n"
    "  return atan(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __atan2(float a1, float a2) {\n"
    "  return atan2f(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline double __atan2(double a1, double a2) {\n"
    "  return atan2(a1, a2);\n"
    "}\n"
    "\n"
    "__device__ inline float __sinh(float a1) {\n"
    "  return sinhf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __sinh(double a1) {\n"
    "  return sinh(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __cosh(float a1) {\n"
    "  return coshf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __cosh(double a1) {\n"
    "  return cosh(a1);\n"
    "}\n"
    "\n"
    "__device__ inline float __tanh(float a1) {\n"
    "  return tanhf(a1);\n"
    "}\n"
    "\n"
    "__device__ inline double __tanh(double a1) {\n"
    "  return tanh(a1);\n"
    "}\n"
    "\n"
    "// Activation functions.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __relu(T a1) {\n"
    "  return a1 > T(0) ? a1 : T(0);\n"
    "}\n"
    "\n"
    "__device__ inline float __sigmoid(float a1) {\n"
    "  return 1.0f / (1.0f + expf(-a1));\n"
    "}\n"
    "\n"
    "__device__ inline double __sigmoid(double a1) {\n"
    "  return 1.0 / (1.0 + exp(-a1));\n"
    "}\n"
    "\n"
    "template <\n"
    "    bool kHasMin = true,\n"
    "    bool kHasMax = true,\n"
    "    typename T,\n"
    "    typename TLo = T,\n"
    "    typename THi = T>\n"
    "__device__ inline T __clamp(T a1, TLo lo, THi hi) {\n"
    "  T result = a1;\n"
    "  if constexpr (kHasMin) {\n"
    "    result = result < static_cast<T>(lo) ? static_cast<T>(lo) : result;\n"
    "  }\n"
    "  if constexpr (kHasMax) {\n"
    "    result = result > static_cast<T>(hi) ? static_cast<T>(hi) : result;\n"
    "  }\n"
    "  return result;\n"
    "}\n"
    "\n"
    "// NaN/Inf replacement.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T\n"
    "__nan_to_num(T a1, double nan_val, double posinf_val, double neginf_val) {\n"
    "  return a1;\n"
    "}\n"
    "\n"
    "__device__ inline float\n"
    "__nan_to_num(float a1, double nan_val, double posinf_val, double neginf_val) {\n"
    "  if (isnan(a1)) {\n"
    "    return static_cast<float>(nan_val);\n"
    "  }\n"
    "  if (isinf(a1)) {\n"
    "    return a1 > 0 ? static_cast<float>(posinf_val)\n"
    "                  : static_cast<float>(neginf_val);\n"
    "  }\n"
    "  return a1;\n"
    "}\n"
    "\n"
    "__device__ inline double\n"
    "__nan_to_num(double a1, double nan_val, double posinf_val, double neginf_val) {\n"
    "  if (isnan(a1)) {\n"
    "    return nan_val;\n"
    "  }\n"
    "  if (isinf(a1)) {\n"
    "    return a1 > 0 ? posinf_val : neginf_val;\n"
    "  }\n"
    "  return a1;\n"
    "}\n"
    "\n"
    "// Min/max.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __minimum(T a1, T a2) {\n"
    "  return a1 < a2 ? a1 : a2;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __maximum(T a1, T a2) {\n"
    "  return a1 > a2 ? a1 : a2;\n"
    "}\n"
    "\n"
    "// Item.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __item(Tensor* self) {\n"
    "  return *storage<T>(self);\n"
    "}\n"
    "\n"
    "// Where.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __where(bool c, T x, T y) {\n"
    "  return c ? x : y;\n"
    "}\n"
    "\n"
    "// Zero / One.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __zero() {\n"
    "  return T(0);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __one() {\n"
    "  return T(1);\n"
    "}\n"
    "\n"
    "template <typename T, typename U>\n"
    "__device__ inline T __one(U /*ignore*/) {\n"
    "  return T(1);\n"
    "}\n"
    "\n"
    "// Arange.\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __arange_start(int64_t idx, T start) {\n"
    "  return idx + start;\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T __arange(int64_t idx) {\n"
    "  return __arange_start<T>(idx, T(0));\n"
    "}\n"
    "\n"
    "// Shape query.\n"
    "\n"
    "__device__ inline int64_t __sym_size(Tensor* self, int64_t dim) {\n"
    "  return self->dims[self->rank - 1 - dim];\n"
    "}\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_Elementwise_cuh_reg =
    registerHeader(velox_experimental_torchwave_Elementwise_cuh);
inline constexpr const char* velox_experimental_torchwave_Scan_cuh =
    "velox/experimental/torchwave/Scan.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/wave/common/Scan.cuh\"\n"
    "\n"
    "// GPU reduction and scan algorithms. Operations like cumsum, exclusive_sum,\n"
    "// masked_select, and sum combine adjacent array elements via three strategies:\n"
    "//\n"
    "// Single-block: one thread block processes the entire array sequentially,\n"
    "// carrying an intermediate sum between block-wide iterations. Low overhead\n"
    "// but limited parallelism.\n"
    "//\n"
    "// Multi-kernel: stage 1 computes per-block partial results in parallel,\n"
    "// stage 2 prefix-sums the partials to produce per-block starting offsets,\n"
    "// stage 3 produces final output using those offsets. Higher throughput than\n"
    "// single-block but more overhead per element.\n"
    "//\n"
    "// Cooperative-grid: same three-stage logic as multi-kernel but uses\n"
    "// device-side inter-block barriers instead of kernel boundaries, avoiding\n"
    "// the launch overhead between stages.\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "template <int32_t kBlockSize, typename T, typename Func>\n"
    "__device__ T reduce(T input, Func func, void* temp) {\n"
    "  constexpr int32_t kNumWarps = kBlockSize / kWarpThreads;\n"
    "\n"
    "  auto* tempT = static_cast<T*>(temp);\n"
    "  // Warp-level reduce.\n"
    "  T warpResult = facebook::velox::wave::WarpReduce<T>().reduce(input, func);\n"
    "\n"
    "  // Lane 0 of each warp stores its result in temp.\n"
    "  if (threadIdx.x % kWarpThreads == 0) {\n"
    "    tempT[threadIdx.x / kWarpThreads] = warpResult;\n"
    "  }\n"
    "  __syncthreads();\n"
    "\n"
    "  // First warp reduces the warp-level results.\n"
    "  if (threadIdx.x < kWarpThreads) {\n"
    "    T val = threadIdx.x < kNumWarps ? tempT[threadIdx.x] : T{};\n"
    "    warpResult =\n"
    "        facebook::velox::wave::WarpReduce<T, kNumWarps>().reduce(val, func);\n"
    "  }\n"
    "  return warpResult;\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void masked_select(\n"
    "    T input,\n"
    "    bool flag,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& counter,\n"
    "    uint32_t idx,\n"
    "    uint32_t size,\n"
    "    BlockInfo& block) {\n"
    "  T* out = storage<T>(output);\n"
    "  if (idx == 0) {\n"
    "    // there is a syncthreads in exclusiveSum before use of counter.\n"
    "    counter = 0;\n"
    "  }\n"
    "  if (idx >= size) {\n"
    "    flag = false;\n"
    "  }\n"
    "  int32_t sum = facebook::velox::wave::inclusiveSum<uint32_t, kBlockSize>(\n"
    "      threadIdx.x == 0 ? static_cast<uint32_t>(flag) + counter\n"
    "                       : static_cast<uint32_t>(flag),\n"
    "      &counter,\n"
    "      static_cast<uint32_t*>(temp));\n"
    "  if (flag) {\n"
    "    out[sum - 1] = input;\n"
    "  }\n"
    "  if (idx == size - 1) {\n"
    "    output->dims[0] = sum;\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void masked_select(\n"
    "    Tensor* input,\n"
    "    Tensor* mask,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& counter,\n"
    "    uint32_t idx,\n"
    "    uint32_t size,\n"
    "    BlockInfo& block) {\n"
    "  bool* flags = storage<bool>(mask);\n"
    "  T* in = storage<T>(input);\n"
    "  masked_select<kBlockSize, T>(\n"
    "      idx < size ? in[idx] : T(),\n"
    "      idx < size ? flags[idx] : false,\n"
    "      output,\n"
    "      temp,\n"
    "      counter,\n"
    "      idx,\n"
    "      size,\n"
    "      block);\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void masked_select_head(\n"
    "    Tensor* input,\n"
    "    Tensor* mask,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  bool* flags = storage<bool>(mask);\n"
    "  int32_t* out = storage<int32_t>(output);\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    uint32_t flag = (idx < size) ? static_cast<uint32_t>(flags[idx]) : 0;\n"
    "    auto count = reduce<kBlockSize, uint32_t>(\n"
    "        flag, [](uint32_t a, uint32_t b) { return a + b; }, temp);\n"
    "    if (threadIdx.x == 0) {\n"
    "      out[blockIdx] = count;\n"
    "      blockIdx += block.numBlocksInOp;\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T = uint32_t, typename T2>\n"
    "__device__ void add_sizes(\n"
    "    Tensor* input,\n"
    "    T2* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    T& counter,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    counter = 0;\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  T* in = storage<T>(input);\n"
    "  for (uint32_t idx = threadIdx.x; idx < rounded; idx += blockDim.x) {\n"
    "    T val = (idx < size) ? in[idx] : T(0);\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += counter;\n"
    "    }\n"
    "    T sum = facebook::velox::wave::inclusiveSum<T, kBlockSize>(\n"
    "        val, nullptr, static_cast<T*>(temp));\n"
    "    if (idx < size) {\n"
    "      in[idx] = sum;\n"
    "    }\n"
    "    if (threadIdx.x == blockDim.x - 1) {\n"
    "      counter = sum;\n"
    "    }\n"
    "    __syncthreads();\n"
    "  }\n"
    "  if (threadIdx.x == 0 && output) {\n"
    "    *output = counter;\n"
    "  }\n"
    "}\n"
    "\n"
    "// Overload without output argument for use as middle stage of cumsum.\n"
    "template <int32_t kBlockSize, typename T = uint32_t>\n"
    "__device__ void add_sizes(\n"
    "    Tensor* input,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    T& counter,\n"
    "    BlockInfo& block) {\n"
    "  add_sizes<kBlockSize, T>(\n"
    "      input, static_cast<T*>(nullptr), temp, size, rounded, counter, block);\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void masked_select_final(\n"
    "    Tensor* input,\n"
    "    Tensor* mask,\n"
    "    Tensor* counts,\n"
    "    int32_t* total,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  T* in = storage<T>(input);\n"
    "  bool* flags = storage<bool>(mask);\n"
    "  int32_t* cnt = storage<int32_t>(counts);\n"
    "  T* out = storage<T>(output);\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    bool flag = (idx < size) ? flags[idx] : false;\n"
    "    auto base = blockIdx == 0 ? 0 : cnt[blockIdx - 1];\n"
    "    int32_t val = static_cast<int32_t>(flag);\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += base;\n"
    "    }\n"
    "    int32_t sum = facebook::velox::wave::inclusiveSum<int32_t, kBlockSize>(\n"
    "        val, nullptr, static_cast<int32_t*>(temp));\n"
    "    if (flag) {\n"
    "      out[sum - 1] = in[idx];\n"
    "    }\n"
    "    if (idx == size - 1) {\n"
    "      output->dims[0] = sum;\n"
    "    }\n"
    "    blockIdx += block.numBlocksInOp;\n"
    "  }\n"
    "}\n"
    "\n"
    "// Single-block cumulative sum. Writes inclusive prefix sum of\n"
    "// input into output. Iterates over the full length of the input.\n"
    "// TIn is the input element type, TOut is the accumulation/output type.\n"
    "// Calling convention: (input, output, dim_attr, shared..., blockInfo).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut, int32_t dim = 0>\n"
    "__device__ void cumsum(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counter,\n"
    "    BlockInfo& /*block*/) {\n"
    "  static_assert(dim == 0, \"Only dim 0 is supported\");\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    counter = 0;\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  for (uint32_t idx = threadIdx.x; idx < rounded; idx += blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += counter;\n"
    "    }\n"
    "    TOut sum = facebook::velox::wave::inclusiveSum<TOut, kBlockSize>(\n"
    "        val, nullptr, static_cast<TOut*>(temp));\n"
    "    if (idx < size) {\n"
    "      out[idx] = sum;\n"
    "    }\n"
    "    if (threadIdx.x == blockDim.x - 1) {\n"
    "      counter = sum;\n"
    "    }\n"
    "    __syncthreads();\n"
    "  }\n"
    "}\n"
    "\n"
    "// Three-stage cumsum, stage 1: compute per-block sums.\n"
    "// TIn is the input element type, TOut is the accumulation type.\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void cumsum_head(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    auto sum = reduce<kBlockSize, TOut>(\n"
    "        val, [](TOut a, TOut b) { return a + b; }, temp);\n"
    "    if (threadIdx.x == 0) {\n"
    "      out[blockIdx] = sum;\n"
    "      blockIdx += block.numBlocksInOp;\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "// Three-stage cumsum, stage 3: compute final inclusive prefix sum using\n"
    "// per-block prefix sums from add_sizes.\n"
    "// TIn is the input element type, TOut is the accumulation/output type.\n"
    "// Calling convention: (input, counts, output, dim_attr, shared..., blockInfo).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut, int32_t dim = 0>\n"
    "__device__ void cumsum_final(\n"
    "    Tensor* input,\n"
    "    Tensor* counts,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  static_assert(dim == 0, \"Only dim 0 is supported\");\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* cnt = storage<TOut>(counts);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    TOut base = blockIdx == 0 ? TOut(0) : cnt[blockIdx - 1];\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += base;\n"
    "    }\n"
    "    TOut sum = facebook::velox::wave::inclusiveSum<TOut, kBlockSize>(\n"
    "        val, nullptr, static_cast<TOut*>(temp));\n"
    "    if (idx < size) {\n"
    "      out[idx] = sum;\n"
    "    }\n"
    "    blockIdx += block.numBlocksInOp;\n"
    "  }\n"
    "}\n"
    "\n"
    "// Single-block exclusive prefix sum. Output has size+1 elements.\n"
    "// out[0] = 0, out[i+1] = sum(in[0..i]).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut, int32_t dim = 0>\n"
    "__device__ void exclusive_sum(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counter,\n"
    "    BlockInfo& /*block*/) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    counter = 0;\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  if (threadIdx.x == 0) {\n"
    "    out[0] = TOut(0);\n"
    "  }\n"
    "  for (uint32_t idx = threadIdx.x; idx < rounded; idx += blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += counter;\n"
    "    }\n"
    "    TOut sum = facebook::velox::wave::inclusiveSum<TOut, kBlockSize>(\n"
    "        val, nullptr, static_cast<TOut*>(temp));\n"
    "    if (idx < size) {\n"
    "      out[idx + 1] = sum;\n"
    "    }\n"
    "    if (threadIdx.x == blockDim.x - 1) {\n"
    "      counter = sum;\n"
    "    }\n"
    "    __syncthreads();\n"
    "  }\n"
    "}\n"
    "\n"
    "// Multi-block exclusive sum, stage 1: per-block sums (same as cumsum_head).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void exclusive_sum_head(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  cumsum_head<kBlockSize, TIn, TOut>(input, output, temp, size, rounded, block);\n"
    "}\n"
    "\n"
    "// Multi-block exclusive sum, stage 3: final exclusive prefix sum.\n"
    "// Output has size+1 elements: out[0]=0, out[i+1]=sum(in[0..i]).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void exclusive_sum_final(\n"
    "    Tensor* input,\n"
    "    Tensor* counts,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* cnt = storage<TOut>(counts);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    TOut base = blockIdx == 0 ? TOut(0) : cnt[blockIdx - 1];\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += base;\n"
    "      out[idx] = base;\n"
    "    }\n"
    "    TOut sum = facebook::velox::wave::inclusiveSum<TOut, kBlockSize>(\n"
    "        val, nullptr, static_cast<TOut*>(temp));\n"
    "    if (idx < size) {\n"
    "      out[idx + 1] = sum;\n"
    "    }\n"
    "    blockIdx += block.numBlocksInOp;\n"
    "  }\n"
    "}\n"
    "\n"
    "// repeat_interleave head stage: compute inclusive prefix sums of repeats into\n"
    "// a separate int32 prefix tensor and write the total to *total.\n"
    "// TRepeats is the element type of the repeats tensor (int32_t or int64_t).\n"
    "template <int32_t kBlockSize, typename TRepeats>\n"
    "__device__ void repeat_interleave_head(\n"
    "    Tensor* repeats,\n"
    "    Tensor* prefix,\n"
    "    int32_t* total,\n"
    "    Int32X32& warpSums,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    uint32_t& counter,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*repeats);\n"
    "    counter = 0;\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TRepeats* in = storage<TRepeats>(repeats);\n"
    "  int32_t* out = storage<int32_t>(prefix);\n"
    "  for (uint32_t idx = threadIdx.x; idx < rounded; idx += blockDim.x) {\n"
    "    uint32_t val = (idx < size) ? static_cast<uint32_t>(in[idx]) : 0;\n"
    "    if (threadIdx.x == 0) {\n"
    "      val += counter;\n"
    "    }\n"
    "    uint32_t sum = facebook::velox::wave::inclusiveSum<uint32_t, kBlockSize>(\n"
    "        val, nullptr, reinterpret_cast<uint32_t*>(&warpSums));\n"
    "    if (idx < size) {\n"
    "      out[idx] = static_cast<int32_t>(sum);\n"
    "    }\n"
    "    if (threadIdx.x == blockDim.x - 1) {\n"
    "      counter = sum;\n"
    "    }\n"
    "    __syncthreads();\n"
    "  }\n"
    "  if (threadIdx.x == 0 && total) {\n"
    "    *total = static_cast<int32_t>(counter);\n"
    "  }\n"
    "}\n"
    "\n"
    "// repeat_interleave final stage: for each element i in self, writes self[i]\n"
    "// into output[prefix[i-1]..prefix[i]). prefix is the inclusive prefix sum of\n"
    "// the repeats tensor. T is the element type of input and output.\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void repeat_interleave_final(\n"
    "    Tensor* input,\n"
    "    Tensor* prefix,\n"
    "    int32_t* /*total*/,\n"
    "    Tensor* output,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  T* in = storage<T>(input);\n"
    "  int32_t* pfx = storage<int32_t>(prefix);\n"
    "  T* out = storage<T>(output);\n"
    "  auto outputSize = numEl(*output);\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    if (idx < size) {\n"
    "      int32_t start = idx == 0 ? 0 : pfx[idx - 1];\n"
    "      int32_t end = pfx[idx];\n"
    "      T val = in[idx];\n"
    "      for (int32_t j = start; j < end; ++j) {\n"
    "        assert(static_cast<uint32_t>(j) < outputSize);\n"
    "        out[j] = val;\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "// Multi-block variant of repeat_interleave_final with an op barrier at the\n"
    "// end for cooperative/multi-kernel grids.\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void repeat_interleave_final_cg(\n"
    "    Tensor* input,\n"
    "    Tensor* prefix,\n"
    "    int32_t* total,\n"
    "    Tensor* output,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    int32_t bar0,\n"
    "    BlockInfo& block) {\n"
    "  repeat_interleave_final<kBlockSize, T>(\n"
    "      input, prefix, total, output, size, rounded, block);\n"
    "  opBarrier(block, bar0);\n"
    "}\n"
    "\n"
    "// Multi-block sum reduction, stage 1: per-block reduction.\n"
    "// Each block reduces its chunk of the input and writes one TOut value.\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void tw_sum_head(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    BlockInfo& block) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  TOut* out = storage<TOut>(output);\n"
    "  uint32_t blockIdx = block.blockInOp;\n"
    "  for (uint32_t idx = block.blockInOp * blockDim.x + threadIdx.x; idx < rounded;\n"
    "       idx += block.numBlocksInOp * blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    auto sum = reduce<kBlockSize, TOut>(\n"
    "        val, [](TOut a, TOut b) { return a + b; }, temp);\n"
    "    if (threadIdx.x == 0) {\n"
    "      out[blockIdx] = sum;\n"
    "      blockIdx += block.numBlocksInOp;\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "// Single-block sum reduction over a tensor. Reduces all elements of input\n"
    "// into a scalar stored in output. counterT accumulates intermediate sums\n"
    "// across iterations. TIn is the input element type, TOut is the\n"
    "// accumulation/output type.\n"
    "// Calling convention: (input, output, shared..., blockInfo).\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void tw_sum_tensor(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counterT,\n"
    "    BlockInfo& /*block*/) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    size = numEl(*input);\n"
    "    rounded = roundUpPwr2(size, kBlockSize);\n"
    "    counterT = TOut(0);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TIn* in = storage<TIn>(input);\n"
    "  for (uint32_t idx = threadIdx.x; idx < rounded; idx += blockDim.x) {\n"
    "    TOut val = (idx < size) ? static_cast<TOut>(in[idx]) : TOut(0);\n"
    "    auto blockSum = reduce<kBlockSize, TOut>(\n"
    "        val, [](TOut a, TOut b) { return a + b; }, temp);\n"
    "    if (threadIdx.x == 0) {\n"
    "      counterT += blockSum;\n"
    "    }\n"
    "    __syncthreads();\n"
    "  }\n"
    "  if (threadIdx.x == 0) {\n"
    "    *storage<TOut>(output) = counterT;\n"
    "  }\n"
    "}\n"
    "\n"
    "// Register-input overload: called per-lane from the caller's loop.\n"
    "// Accumulates block-reduced sums across iterations. On the last iteration\n"
    "// (idx at the last stride-aligned position), lane 0 writes the total to output.\n"
    "// TIn is the input element type, TOut is the accumulation/output type.\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void tw_sum(\n"
    "    TIn in,\n"
    "    Tensor* output,\n"
    "    void* temp,\n"
    "    TOut& counterT,\n"
    "    uint32_t idx,\n"
    "    uint32_t size,\n"
    "    BlockInfo& /*block*/) {\n"
    "  if (idx == 0) {\n"
    "    counterT = TOut(0);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  TOut val = static_cast<TOut>(in);\n"
    "  auto blockSum =\n"
    "      reduce<kBlockSize, TOut>(val, [](TOut a, TOut b) { return a + b; }, temp);\n"
    "  if (threadIdx.x == 0) {\n"
    "    counterT += blockSum;\n"
    "  }\n"
    "  __syncthreads();\n"
    "  if (threadIdx.x == 0 && idx + kBlockSize >= size) {\n"
    "    *storage<TOut>(output) = counterT;\n"
    "  }\n"
    "}\n"
    "\n"
    "// --- Cooperative grid variants ---\n"
    "\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut, int32_t dim = 0>\n"
    "__device__ void cumsum_cg(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    Tensor* counts,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counter,\n"
    "    int32_t bar0,\n"
    "    int32_t bar1,\n"
    "    BlockInfo& block) {\n"
    "  cumsum_head<kBlockSize, TIn, TOut>(input, counts, temp, size, rounded, block);\n"
    "  opBarrier(block, bar0);\n"
    "  if (block.blockInOp == 0) {\n"
    "    add_sizes<kBlockSize, TOut>(counts, temp, size, rounded, counter, block);\n"
    "  }\n"
    "  opBarrier(block, bar1);\n"
    "  cumsum_final<kBlockSize, TIn, TOut, dim>(\n"
    "      input, counts, output, temp, size, rounded, block);\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void exclusive_sum_cg(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    Tensor* counts,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counter,\n"
    "    int32_t bar0,\n"
    "    int32_t bar1,\n"
    "    BlockInfo& block) {\n"
    "  exclusive_sum_head<kBlockSize, TIn, TOut>(\n"
    "      input, counts, temp, size, rounded, block);\n"
    "  opBarrier(block, bar0);\n"
    "  if (block.blockInOp == 0) {\n"
    "    add_sizes<kBlockSize, TOut>(counts, temp, size, rounded, counter, block);\n"
    "  }\n"
    "  opBarrier(block, bar1);\n"
    "  exclusive_sum_final<kBlockSize, TIn, TOut>(\n"
    "      input, counts, output, temp, size, rounded, block);\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename T>\n"
    "__device__ void masked_select_cg(\n"
    "    Tensor* input,\n"
    "    Tensor* mask,\n"
    "    Tensor* output,\n"
    "    Tensor* counts,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    uint32_t& counter,\n"
    "    int32_t bar0,\n"
    "    int32_t bar1,\n"
    "    int32_t bar2,\n"
    "    BlockInfo& block) {\n"
    "  masked_select_head<kBlockSize, T>(\n"
    "      input, mask, counts, temp, size, rounded, block);\n"
    "  opBarrier(block, bar0);\n"
    "  if (block.blockInOp == 0) {\n"
    "    add_sizes<kBlockSize>(\n"
    "        counts,\n"
    "        static_cast<int32_t*>(nullptr),\n"
    "        temp,\n"
    "        size,\n"
    "        rounded,\n"
    "        counter,\n"
    "        block);\n"
    "  }\n"
    "  opBarrier(block, bar1);\n"
    "  masked_select_final<kBlockSize, T>(\n"
    "      input,\n"
    "      mask,\n"
    "      counts,\n"
    "      static_cast<int32_t*>(nullptr),\n"
    "      output,\n"
    "      temp,\n"
    "      size,\n"
    "      rounded,\n"
    "      block);\n"
    "  opBarrier(block, bar2);\n"
    "}\n"
    "\n"
    "template <int32_t kBlockSize, typename TIn, typename TOut>\n"
    "__device__ void tw_sum_cg(\n"
    "    Tensor* input,\n"
    "    Tensor* output,\n"
    "    Tensor* partials,\n"
    "    void* temp,\n"
    "    uint32_t& size,\n"
    "    uint32_t& rounded,\n"
    "    TOut& counterT,\n"
    "    int32_t bar0,\n"
    "    int32_t bar1,\n"
    "    BlockInfo& block) {\n"
    "  tw_sum_head<kBlockSize, TIn, TOut>(\n"
    "      input, partials, temp, size, rounded, block);\n"
    "  opBarrier(block, bar0);\n"
    "  if (block.blockInOp == 0) {\n"
    "    tw_sum_tensor<kBlockSize, TOut, TOut>(\n"
    "        partials, output, temp, size, rounded, counterT, block);\n"
    "  }\n"
    "  opBarrier(block, bar1);\n"
    "}\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_Scan_cuh_reg =
    registerHeader(velox_experimental_torchwave_Scan_cuh);
inline constexpr const char* velox_experimental_torchwave_Views_cuh =
    "velox/experimental/torchwave/Views.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/torchwave/KernelParams.h\"\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "#ifdef __CUDACC__\n"
    "\n"
    "// Computes a view of 'input' with the shape given by 'shape' and writes the\n"
    "// result into 'output'. The output shares storage with the input. A -1 in\n"
    "// shape.data means infer that dimension from the input's total element count.\n"
    "// Uses Tensor::synchronized so that concurrent blocks calling this on the same\n"
    "// output safely execute only once.\n"
    "__device__ inline void tw_view(\n"
    "    Tensor* input,\n"
    "    const ScalarList& shape,\n"
    "    Tensor* output,\n"
    "    BlockInfo& /*block*/) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    output->synchronized([&]() {\n"
    "      output->storage = input->storage;\n"
    "      output->rank = shape.size;\n"
    "\n"
    "      uint32_t totalNumEl = 1;\n"
    "      for (int i = 0; i < input->rank; ++i) {\n"
    "        totalNumEl *= input->dims[i];\n"
    "      }\n"
    "\n"
    "      int32_t inferIdx = -1;\n"
    "      int32_t knownProduct = 1;\n"
    "      for (int i = 0; i < shape.size; ++i) {\n"
    "        if (shape.data[i] == -1) {\n"
    "          inferIdx = i;\n"
    "        } else {\n"
    "          output->dims[i] = shape.data[i];\n"
    "          knownProduct *= shape.data[i];\n"
    "        }\n"
    "      }\n"
    "      if (inferIdx >= 0) {\n"
    "        output->dims[inferIdx] =\n"
    "            knownProduct == 0 ? 0 : totalNumEl / knownProduct;\n"
    "      }\n"
    "\n"
    "      // Contiguous strides: innermost dim has stride 1.\n"
    "      if (shape.size > 0) {\n"
    "        output->strides[shape.size - 1] = 1;\n"
    "        for (int i = shape.size - 2; i >= 0; --i) {\n"
    "          output->strides[i] = output->strides[i + 1] * output->dims[i + 1];\n"
    "        }\n"
    "      }\n"
    "\n"
    "      output->numEl = totalNumEl;\n"
    "      output->contiguous = true;\n"
    "    });\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "// Reshape is the same operation as view at the kernel level: both produce a\n"
    "// contiguous view with new dims and strides computed from the shape.\n"
    "__device__ inline void tw_reshape(\n"
    "    Tensor* input,\n"
    "    const ScalarList& shape,\n"
    "    Tensor* output,\n"
    "    BlockInfo& block) {\n"
    "  tw_view(input, shape, output, block);\n"
    "}\n"
    "\n"
    "// Selects a single element along dimension 'dim' at position 'index',\n"
    "// reducing the rank by one. The output shares storage with the input.\n"
    "template <typename T>\n"
    "__device__ inline void tw_select(\n"
    "    Tensor* input,\n"
    "    int64_t dim,\n"
    "    int64_t index,\n"
    "    Tensor* output,\n"
    "    BlockInfo& /*block*/) {\n"
    "  if (threadIdx.x == 0) {\n"
    "    output->synchronized([&]() {\n"
    "      if (dim < 0) {\n"
    "        dim += input->rank;\n"
    "      }\n"
    "      if (index < 0) {\n"
    "        index += input->dims[dim];\n"
    "      }\n"
    "      output->storage = reinterpret_cast<char*>(\n"
    "          static_cast<T*>(input->storage) +\n"
    "          static_cast<int64_t>(index) * input->strides[dim]);\n"
    "      output->rank = input->rank - 1;\n"
    "      int out_i = 0;\n"
    "      for (int i = 0; i < input->rank; ++i) {\n"
    "        if (i == dim) {\n"
    "          continue;\n"
    "        }\n"
    "        output->dims[out_i] = input->dims[i];\n"
    "        output->strides[out_i] = input->strides[i];\n"
    "        ++out_i;\n"
    "      }\n"
    "      uint32_t n = 1;\n"
    "      for (int i = 0; i < output->rank; ++i) {\n"
    "        n *= output->dims[i];\n"
    "      }\n"
    "      output->numEl = n;\n"
    "      output->contiguous = output->isContiguous();\n"
    "    });\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "// Makes 'dest' a 1D view of 'src' starting at 'elementOffset' elements.\n"
    "// 'elementSize' is sizeof the element type (e.g. 4 for float).\n"
    "__device__ inline void\n"
    "__view(Tensor& src, int32_t elementOffset, int32_t elementSize, Tensor& dest) {\n"
    "  dest.storage = static_cast<char*>(src.storage) +\n"
    "      static_cast<int64_t>(elementOffset) * elementSize;\n"
    "  dest.status = Tensor::kInited;\n"
    "}\n"
    "\n"
    "#endif\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_Views_cuh_reg =
    registerHeader(velox_experimental_torchwave_Views_cuh);
inline constexpr const char* velox_experimental_torchwave_Hash_cuh =
    "velox/experimental/torchwave/Hash.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/torchwave/KernelParams.h\"\n"
    "\n"
    "namespace torch::wave {\n"
    "\n"
    "// GPU hash table for the isin() operation. Uses 0 as the empty sentinel,\n"
    "// so element 0 is handled separately: slot 0 of the table is reserved as\n"
    "// a flag indicating whether 0 is actually in the set.\n"
    "\n"
    "#ifdef __CUDACC__\n"
    "\n"
    "constexpr int64_t kEmpty = 0;\n"
    "\n"
    "__device__ inline uint32_t hashInt(int64_t val) {\n"
    "  uint64_t v = static_cast<uint64_t>(val);\n"
    "  v = (v ^ (v >> 30)) * 0xbf58476d1ce4e5b9ULL;\n"
    "  v = (v ^ (v >> 27)) * 0x94d049bb133111ebULL;\n"
    "  return static_cast<uint32_t>(v ^ (v >> 31));\n"
    "}\n"
    "\n"
    "__device__ inline int32_t\n"
    "atomicCAS_T(int32_t* addr, int32_t compare, int32_t val) {\n"
    "  return atomicCAS(addr, compare, val);\n"
    "}\n"
    "\n"
    "__device__ inline int64_t\n"
    "atomicCAS_T(int64_t* addr, int64_t compare, int64_t val) {\n"
    "  return static_cast<int64_t>(atomicCAS(\n"
    "      reinterpret_cast<unsigned long long*>(addr),\n"
    "      static_cast<unsigned long long>(compare),\n"
    "      static_cast<unsigned long long>(val)));\n"
    "}\n"
    "\n"
    "// Element 0 of the table is a flag: non-zero means kEmpty is in the set.\n"
    "// The hash table entries start at table[1]. The hash mask is tableSize - 2\n"
    "// because the power-of-two portion is tableSize - 1 elements.\n"
    "template <typename T>\n"
    "__device__ inline void\n"
    "tw_isin_head(Tensor* input, Tensor* output, BlockInfo& /*block*/) {\n"
    "  T* table = storage<T>(output);\n"
    "  int32_t tableSize = output->numEl;\n"
    "  uint32_t mask = static_cast<uint32_t>(tableSize - 2);\n"
    "  T* in = storage<T>(input);\n"
    "  int32_t n = numEl(*input);\n"
    "\n"
    "  for (auto i = threadIdx.x; i < tableSize; i += blockDim.x) {\n"
    "    table[i] = 0;\n"
    "  }\n"
    "  __syncthreads();\n"
    "\n"
    "  for (auto i = threadIdx.x; i < n; i += blockDim.x) {\n"
    "    T val = in[i];\n"
    "    if (val == static_cast<T>(kEmpty)) {\n"
    "      table[0] = 1;\n"
    "      continue;\n"
    "    }\n"
    "    uint32_t h = hashInt(static_cast<int64_t>(val)) & mask;\n"
    "    for (uint32_t iter = 0; iter < static_cast<uint32_t>(tableSize); ++iter) {\n"
    "      T old = atomicCAS_T(&table[h + 1], static_cast<T>(0), val);\n"
    "      if (old == 0 || old == val) {\n"
    "        break;\n"
    "      }\n"
    "      h = (h + 1) & mask;\n"
    "      assert(iter + 1 < static_cast<uint32_t>(tableSize));\n"
    "    }\n"
    "  }\n"
    "  __threadfence();\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline bool\n"
    "__isin_final(uint32_t idx, uint32_t size, T val, Tensor* hashTable, bool inv) {\n"
    "  if (idx >= size) {\n"
    "    return false;\n"
    "  }\n"
    "  T* table = storage<T>(hashTable);\n"
    "  bool found;\n"
    "  if (val == static_cast<T>(kEmpty)) {\n"
    "    found = table[0] != 0;\n"
    "  } else {\n"
    "    found = false;\n"
    "    int32_t tableSize = hashTable->numEl;\n"
    "    uint32_t mask = static_cast<uint32_t>(tableSize - 2);\n"
    "    uint32_t h = hashInt(static_cast<int64_t>(val)) & mask;\n"
    "    for (uint32_t iter = 0; iter < static_cast<uint32_t>(tableSize); ++iter) {\n"
    "      T entry = table[h + 1];\n"
    "      if (entry == 0) {\n"
    "        break;\n"
    "      }\n"
    "      if (entry == val) {\n"
    "        found = true;\n"
    "        break;\n"
    "      }\n"
    "      h = (h + 1) & mask;\n"
    "      assert(iter + 1 < static_cast<uint32_t>(tableSize));\n"
    "    }\n"
    "  }\n"
    "  return inv ? !found : found;\n"
    "}\n"
    "\n"
    "#endif\n"
    "\n"
    "} // namespace torch::wave\n";
inline bool velox_experimental_torchwave_Hash_cuh_reg =
    registerHeader(velox_experimental_torchwave_Hash_cuh);
} // namespace facebook::velox::wave
