/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "velox/common/base/tests/GTestUtils.h"
#include "velox/functions/sparksql/tests/SparkFunctionBaseTest.h"

namespace facebook::velox::functions::sparksql::test {
namespace {

using namespace facebook::velox::test;

// All expectations below were generated by running Spark 3.5.1's
// ParseUrl (java.net.URI based) against the same inputs, so they pin the
// implementation to Java semantics rather than RFC 3986.
class ParseUrlTest : public SparkFunctionBaseTest {
 public:
  std::optional<std::string> parseUrl(
      const std::optional<std::string>& url,
      const std::string& part) {
    return evaluateOnce<std::string>(
        fmt::format("parse_url(c0, '{}')", part), url);
  }

  std::optional<std::string> parseUrlQuery(
      const std::optional<std::string>& url,
      const std::optional<std::string>& key) {
    return evaluateOnce<std::string>("parse_url(c0, 'QUERY', c1)", url, key);
  }
};

TEST_F(ParseUrlTest, allParts) {
  // A URL that carries every component Spark recognizes. Mirrors the first
  // case in Spark's UrlFunctionsSuite.
  const auto fullUrl = "http://userinfo@spark.apache.org/path?query=1#Ref";
  EXPECT_EQ("spark.apache.org", parseUrl(fullUrl, "HOST"));
  EXPECT_EQ("/path", parseUrl(fullUrl, "PATH"));
  EXPECT_EQ("query=1", parseUrl(fullUrl, "QUERY"));
  EXPECT_EQ("Ref", parseUrl(fullUrl, "REF"));
  EXPECT_EQ("http", parseUrl(fullUrl, "PROTOCOL"));
  EXPECT_EQ("/path?query=1", parseUrl(fullUrl, "FILE"));
  EXPECT_EQ("userinfo@spark.apache.org", parseUrl(fullUrl, "AUTHORITY"));
  EXPECT_EQ("userinfo", parseUrl(fullUrl, "USERINFO"));
  EXPECT_EQ("1", parseUrlQuery(fullUrl, "query"));

  // Percent-encoding is preserved verbatim; Spark does not decode it.
  const auto encodedUrl =
      "https://use%20r:pas%20s@example.com/dir%20/pa%20th.HTML?query=x%20y&q2=2#Ref%20two";
  EXPECT_EQ("example.com", parseUrl(encodedUrl, "HOST"));
  EXPECT_EQ("/dir%20/pa%20th.HTML", parseUrl(encodedUrl, "PATH"));
  EXPECT_EQ("query=x%20y&q2=2", parseUrl(encodedUrl, "QUERY"));
  EXPECT_EQ("Ref%20two", parseUrl(encodedUrl, "REF"));
  EXPECT_EQ("https", parseUrl(encodedUrl, "PROTOCOL"));
  EXPECT_EQ(
      "/dir%20/pa%20th.HTML?query=x%20y&q2=2", parseUrl(encodedUrl, "FILE"));
  EXPECT_EQ("use%20r:pas%20s@example.com", parseUrl(encodedUrl, "AUTHORITY"));
  EXPECT_EQ("use%20r:pas%20s", parseUrl(encodedUrl, "USERINFO"));
  EXPECT_EQ("x%20y", parseUrlQuery(encodedUrl, "query"));

  // A URL with no path. Spark returns an empty string (not null) for PATH
  // and FILE; QUERY and REF are absent, so they are null.
  const auto noPathUrl = "http://user:pass@host";
  EXPECT_EQ("host", parseUrl(noPathUrl, "HOST"));
  EXPECT_EQ("", parseUrl(noPathUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl(noPathUrl, "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl(noPathUrl, "REF"));
  EXPECT_EQ("http", parseUrl(noPathUrl, "PROTOCOL"));
  EXPECT_EQ("", parseUrl(noPathUrl, "FILE"));
  EXPECT_EQ("user:pass@host", parseUrl(noPathUrl, "AUTHORITY"));
  EXPECT_EQ("user:pass", parseUrl(noPathUrl, "USERINFO"));
  EXPECT_EQ(std::nullopt, parseUrlQuery(noPathUrl, "query"));

  // Root path with an empty query and an empty fragment. Both are present,
  // so Spark returns empty strings rather than null.
  const auto rootUrl = "http://user:pass@host/?#";
  EXPECT_EQ("host", parseUrl(rootUrl, "HOST"));
  EXPECT_EQ("/", parseUrl(rootUrl, "PATH"));
  EXPECT_EQ("", parseUrl(rootUrl, "QUERY"));
  EXPECT_EQ("", parseUrl(rootUrl, "REF"));
  EXPECT_EQ("http", parseUrl(rootUrl, "PROTOCOL"));
  EXPECT_EQ("/?", parseUrl(rootUrl, "FILE"));
  EXPECT_EQ("user:pass@host", parseUrl(rootUrl, "AUTHORITY"));
  EXPECT_EQ("user:pass", parseUrl(rootUrl, "USERINFO"));
  EXPECT_EQ(std::nullopt, parseUrlQuery(rootUrl, "query"));

  // A matrix-style ";param" path segment and a ';' inside the query string.
  const auto paramUrl = "http://user:pass@host/file;param?query;p2";
  EXPECT_EQ("host", parseUrl(paramUrl, "HOST"));
  EXPECT_EQ("/file;param", parseUrl(paramUrl, "PATH"));
  EXPECT_EQ("query;p2", parseUrl(paramUrl, "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl(paramUrl, "REF"));
  EXPECT_EQ("http", parseUrl(paramUrl, "PROTOCOL"));
  EXPECT_EQ("/file;param?query;p2", parseUrl(paramUrl, "FILE"));
  EXPECT_EQ("user:pass@host", parseUrl(paramUrl, "AUTHORITY"));
  EXPECT_EQ("user:pass", parseUrl(paramUrl, "USERINFO"));

  // A URL without an authority has no host component. Java URI.getHost()
  // returns null for such URLs and boost::urls::url.host() would return an
  // empty string, so HOST must be null while the path still resolves.
  const auto noAuthorityUrl = "mailto:John.Doe@example.com";
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "HOST"));
  EXPECT_EQ("mailto", parseUrl(noAuthorityUrl, "PROTOCOL"));

  // An opaque URI has no path, query, or authority at all; only the scheme
  // and the fragment exist.
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl(noAuthorityUrl, "USERINFO"));
  EXPECT_EQ("f", parseUrl("mailto:a@b#f", "REF"));
  EXPECT_EQ("mailto", parseUrl("mailto:a@b#f", "PROTOCOL"));

  // An invalid URL yields null for every part. The ANSI-on error path is a
  // Spark-layer concern (the Velox function has no ANSI mode), so only the
  // ANSI-off behavior is asserted here.
  const auto invalidUrl = "inva lid://user:pass@host/file;param?query;p2";
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "REF"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl(invalidUrl, "USERINFO"));

  // Part matching is exact and case sensitive; unknown parts return null.
  EXPECT_EQ("http", parseUrl(fullUrl, "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl(fullUrl, "protocol"));
  EXPECT_EQ(std::nullopt, parseUrl(fullUrl, "UNKNOWN"));
}

// Covers empty input and scheme-less relative URLs, both accepted by
// java.net.URI but rejected by strict RFC 3986.
TEST_F(ParseUrlTest, emptyAndRelativeUrls) {
  // java.net.URI accepts the empty string; the path is present but empty.
  EXPECT_EQ("", parseUrl("", "PATH"));
  EXPECT_EQ("", parseUrl("", "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl("", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("", "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl("", "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl("", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("", "USERINFO"));

  // A protocol-relative URL.
  const auto protoRelativeUrl = "//p0.example.net/img/x.jpg";
  EXPECT_EQ("p0.example.net", parseUrl(protoRelativeUrl, "HOST"));
  EXPECT_EQ("/img/x.jpg", parseUrl(protoRelativeUrl, "PATH"));
  EXPECT_EQ("/img/x.jpg", parseUrl(protoRelativeUrl, "FILE"));
  EXPECT_EQ("p0.example.net", parseUrl(protoRelativeUrl, "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl(protoRelativeUrl, "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl(protoRelativeUrl, "USERINFO"));

  // A bare absolute path with a query.
  const auto pathOnlyUrl = "/downloads/x?utm=1&from=1";
  EXPECT_EQ("/downloads/x", parseUrl(pathOnlyUrl, "PATH"));
  EXPECT_EQ("utm=1&from=1", parseUrl(pathOnlyUrl, "QUERY"));
  EXPECT_EQ("/downloads/x?utm=1&from=1", parseUrl(pathOnlyUrl, "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl(pathOnlyUrl, "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl(pathOnlyUrl, "AUTHORITY"));

  // A plain opaque-ish token is a valid relative reference whose path is
  // the token itself. A colon inside a relative path is fine.
  EXPECT_EQ(
      "c0ffee1234567890abcdef0123456789",
      parseUrl("c0ffee1234567890abcdef0123456789", "PATH"));
  EXPECT_EQ("./x:y", parseUrl("./x:y", "PATH"));
  EXPECT_EQ("%41", parseUrl("%41", "PATH"));
}

// A second '#' inside the fragment makes the whole URI invalid, so every
// part is null. A single '#' with an empty fragment is fine.
TEST_F(ParseUrlTest, doubleHashFragment) {
  const auto spaUrl =
      "https://spa.example.com/#/page/orders#/order/unprocessed";
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "REF"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl(spaUrl, "USERINFO"));

  EXPECT_EQ(std::nullopt, parseUrl("#a#b", "REF"));
  EXPECT_EQ(std::nullopt, parseUrl("#a#b", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("a#b#c", "REF"));

  // An empty fragment is present, so REF is an empty string rather than
  // null, and the URI itself is valid.
  EXPECT_EQ("https", parseUrl("https://x.com/#", "PROTOCOL"));
  EXPECT_EQ("x.com", parseUrl("https://x.com/#", "HOST"));
  EXPECT_EQ("/", parseUrl("https://x.com/#", "PATH"));
  EXPECT_EQ("", parseUrl("https://x.com/#", "REF"));
  EXPECT_EQ("/", parseUrl("https://x.com/#", "FILE"));
}

// Covers mismatch categories D (non-ASCII characters) and E (brackets).
// java.net.URI allows unencoded non-ASCII characters and '[]' in queries.
TEST_F(ParseUrlTest, nonAsciiAndSpecialChars) {
  const auto cjkUrl = "https://api.example.com/search?q=\u7f8e\u56e2&userid=1";
  EXPECT_EQ("api.example.com", parseUrl(cjkUrl, "HOST"));
  EXPECT_EQ("/search", parseUrl(cjkUrl, "PATH"));
  EXPECT_EQ("q=\u7f8e\u56e2&userid=1", parseUrl(cjkUrl, "QUERY"));
  EXPECT_EQ("/search?q=\u7f8e\u56e2&userid=1", parseUrl(cjkUrl, "FILE"));

  // Non-ASCII characters are not valid in hostnames, so the authority falls
  // back to registry-based form and the host is null.
  EXPECT_EQ(std::nullopt, parseUrl("http://\u4e2d\u6587/p", "HOST"));
  EXPECT_EQ("/p", parseUrl("http://\u4e2d\u6587/p", "PATH"));
  EXPECT_EQ("\u4e2d\u6587", parseUrl("http://\u4e2d\u6587/p", "AUTHORITY"));

  // Brackets are allowed in queries but not in paths.
  const auto bracketUrl = "https://host/path?ids=[626]&ft=1";
  EXPECT_EQ("ids=[626]&ft=1", parseUrl(bracketUrl, "QUERY"));
  EXPECT_EQ("/path", parseUrl(bracketUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("http://h/p[/q", "PATH"));

  // Control characters and spaces make the whole URI invalid.
  EXPECT_EQ(std::nullopt, parseUrl("http://h/p?a=\t", "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a b/p", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("a b", "PATH"));

  // Malformed escape pairs make the whole URI invalid, while well-formed
  // ones pass through undecoded.
  EXPECT_EQ(std::nullopt, parseUrl("http://h/p?a=%Gx", "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://h/p?a=%", "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl("a%4", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("a%zz", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a%zz.com/", "HOST"));

  // Invalid UTF-8 sequences are accepted like ordinary non-ASCII
  // characters: Spark decodes the bytes into a Java string before
  // java.net.URI parses it, and the resulting replacement character is
  // neither a space nor an ISO control character. A truncated 3-byte
  // sequence, a stray continuation byte, and a UTF-8-encoded surrogate
  // are all accepted the same way. The extracted part keeps the original
  // bytes rather than re-encoding them as U+FFFD.
  EXPECT_EQ("a=\xE4\xB8x", parseUrl("http://h/p?a=\xE4\xB8x", "QUERY"));
  EXPECT_EQ(
      "a=\xE4\xB8", parseUrl(std::string("http://h/p?a=\xE4\xB8"), "QUERY"));
  EXPECT_EQ("a=\xB4", parseUrl(std::string("http://h/p?a=\xB4"), "QUERY"));
  EXPECT_EQ(
      "a=\xED\xA0\x80",
      parseUrl(std::string("http://h/p?a=\xED\xA0\x80"), "QUERY"));
  EXPECT_EQ("/p\xE4\xB8", parseUrl(std::string("http://h/p\xE4\xB8"), "PATH"));
}

// An empty authority yields a null HOST rather than an empty string, and
// 'http://' with nothing else is invalid.
TEST_F(ParseUrlTest, emptyAuthority) {
  const auto fileUrl = "file:///C:/Users/x/AppData/Temp/%E4%BC%81.png";
  EXPECT_EQ(std::nullopt, parseUrl(fileUrl, "HOST"));
  EXPECT_EQ("file", parseUrl(fileUrl, "PROTOCOL"));
  EXPECT_EQ(
      "/C:/Users/x/AppData/Temp/%E4%BC%81.png", parseUrl(fileUrl, "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl(fileUrl, "AUTHORITY"));

  EXPECT_EQ(std::nullopt, parseUrl("http:///p", "HOST"));
  EXPECT_EQ("http", parseUrl("http:///p", "PROTOCOL"));
  EXPECT_EQ("/p", parseUrl("http:///p", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("http:///p", "AUTHORITY"));

  // '//' with nothing after it fails to parse entirely.
  EXPECT_EQ(std::nullopt, parseUrl("http://", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("a://", "PATH"));

  // An empty authority followed by a query or fragment is fine.
  EXPECT_EQ(std::nullopt, parseUrl("http://?q", "HOST"));
  EXPECT_EQ("", parseUrl("http://?q", "PATH"));
  EXPECT_EQ("q", parseUrl("http://?q", "QUERY"));
  EXPECT_EQ("?q", parseUrl("http://?q", "FILE"));
  EXPECT_EQ(std::nullopt, parseUrl("http://?q", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://#f", "HOST"));
  EXPECT_EQ("f", parseUrl("http://#f", "REF"));
}

// Pins java.net.URI's authority parsing quirks that surfaced in the
// mismatch analysis: server-based vs registry-based authority fallback.
TEST_F(ParseUrlTest, javaAuthorityEdgeCases) {
  // Port parsing.
  EXPECT_EQ("h", parseUrl("http://h:", "HOST"));
  EXPECT_EQ("h:", parseUrl("http://h:", "AUTHORITY"));
  EXPECT_EQ("h", parseUrl("http://h:80", "HOST"));
  EXPECT_EQ("h:80", parseUrl("http://h:80", "AUTHORITY"));
  // A non-numeric port makes the authority registry-based: the authority
  // is still returned but the host is null.
  EXPECT_EQ(std::nullopt, parseUrl("http://h:x", "HOST"));
  EXPECT_EQ("h:x", parseUrl("http://h:x", "AUTHORITY"));
  EXPECT_EQ("", parseUrl("http://h:x", "PATH"));

  // IPv6 literals.
  EXPECT_EQ("[::1]", parseUrl("http://[::1]/p", "HOST"));
  EXPECT_EQ("[::1]", parseUrl("http://[::1]/p", "AUTHORITY"));
  EXPECT_EQ("[::1]", parseUrl("http://[::1]:8080/p", "HOST"));
  EXPECT_EQ("[::1]:8080", parseUrl("http://[::1]:8080/p", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://[::1]x/", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://[::1]:x/", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://[zz]/p", "HOST"));

  // Characters outside the server-based grammar fall back to a
  // registry-based authority: AUTHORITY is returned but HOST and USERINFO
  // are null.
  EXPECT_EQ(std::nullopt, parseUrl("http://a_b/p", "HOST"));
  EXPECT_EQ("a_b", parseUrl("http://a_b/p", "AUTHORITY"));
  EXPECT_EQ("/p", parseUrl("http://a_b/p", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a@b@c/p", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a@b@c/p", "USERINFO"));
  EXPECT_EQ("a@b@c", parseUrl("http://a@b@c/p", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a%2eb.com/p", "HOST"));
  EXPECT_EQ("a%2eb.com", parseUrl("http://a%2eb.com/p", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://h%20i/", "HOST"));
  EXPECT_EQ("h%20i", parseUrl("http://h%20i/", "AUTHORITY"));
  // In the '%' - permitting server mask a '%' is a mask member, so the
  // malformed pair below survives the server pre-scan and fails via the
  // reg-name scan's escape validation - the JDK throws from there too.
  EXPECT_EQ(std::nullopt, parseUrl("http://a%.com/p", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a%.com/p", "AUTHORITY"));
  // A multi-byte character scans as a server character (non-space,
  // non-control) but still fails parseServer's hostname grammar, so the
  // authority ends up registry-based with a null host.
  EXPECT_EQ(std::nullopt, parseUrl("http://a中b.com/p", "HOST"));
  EXPECT_EQ("a中b.com", parseUrl("http://a中b.com/p", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://-h/", "HOST"));
  EXPECT_EQ("-h", parseUrl("http://-h/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://h-/", "HOST"));
  EXPECT_EQ("h-", parseUrl("http://h-/", "AUTHORITY"));

  // Hostnames with multiple labels must start the last label with a
  // letter unless the host is a well-formed IPv4 address.
  EXPECT_EQ("1.2.3.4", parseUrl("http://1.2.3.4/", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://1.2.3/", "HOST"));
  EXPECT_EQ("1.2.3", parseUrl("http://1.2.3/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://999.1.1.1/", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://1.2.3.999/", "HOST"));
  // Byte values that overflow a Java int fail the address in the JDK
  // (Integer.parseInt throws); the host falls back to registry form.
  EXPECT_EQ(std::nullopt, parseUrl("http://4294967296.0.0.1/", "HOST"));
  EXPECT_EQ(
      "4294967296.0.0.1", parseUrl("http://4294967296.0.0.1/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://99999999999.0.0.1/", "HOST"));
  EXPECT_EQ(
      "99999999999.0.0.1", parseUrl("http://99999999999.0.0.1/", "AUTHORITY"));

  // Userinfo handling.
  EXPECT_EQ("h", parseUrl("http://user@h/", "HOST"));
  EXPECT_EQ("user", parseUrl("http://user@h/", "USERINFO"));
  EXPECT_EQ("", parseUrl("http://@h/", "USERINFO"));
  // The userinfo grammar rejects '@' (unlike pchar), so a second '@'
  // fails the userinfo check; the registry fallback takes over and
  // returns no host or userinfo.
  EXPECT_EQ(std::nullopt, parseUrl("http://u@h@x/", "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl("http://u@h@x/", "USERINFO"));
  EXPECT_EQ("u@h@x", parseUrl("http://u@h@x/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://u@/", "HOST"));
  EXPECT_EQ("u@", parseUrl("http://u@/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://u@/", "USERINFO"));
  EXPECT_EQ(std::nullopt, parseUrl("http://use r@h/", "HOST"));

  // Brackets outside an IPv6 literal are not accepted anywhere in the
  // authority.
  EXPECT_EQ(std::nullopt, parseUrl("http://]/", "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl("http://a]b/", "AUTHORITY"));
}

// Pins java.net.URI's scheme and component-presence edge cases.
TEST_F(ParseUrlTest, javaSchemeAndComponentEdgeCases) {
  // The scheme is returned with its original casing and must start with a
  // letter.
  EXPECT_EQ("HTTP", parseUrl("HTTP://x/p", "PROTOCOL"));
  EXPECT_EQ("x", parseUrl("HTTP://x/p", "HOST"));
  EXPECT_EQ("HTTP", parseUrl("HTTP://x", "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl("1a:x", "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl("x:", "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl(":x", "PROTOCOL"));

  // An opaque URI: everything after the scheme is the scheme-specific
  // part, so only PROTOCOL (and REF if present) are non-null.
  EXPECT_EQ("x", parseUrl("x:y:z", "PROTOCOL"));
  EXPECT_EQ(std::nullopt, parseUrl("x:y:z", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("x:y:z", "QUERY"));
  EXPECT_EQ(std::nullopt, parseUrl("x:y:z", "AUTHORITY"));

  // Empty query and fragment markers are returned as empty strings.
  EXPECT_EQ("", parseUrl("http://h/p?", "QUERY"));
  EXPECT_EQ("/p?", parseUrl("http://h/p?", "FILE"));
  EXPECT_EQ("", parseUrl("http://h/p#", "REF"));
  EXPECT_EQ("/p", parseUrl("http://h/p#", "FILE"));
  EXPECT_EQ("/p?", parseUrl("http://h/p?#", "FILE"));
  EXPECT_EQ("", parseUrl("?", "PATH"));
  EXPECT_EQ("", parseUrl("?", "QUERY"));
  EXPECT_EQ("?", parseUrl("?", "FILE"));
  EXPECT_EQ("", parseUrl("#", "PATH"));
  EXPECT_EQ("", parseUrl("#", "REF"));

  // Path-only and authority-only forms.
  EXPECT_EQ("h", parseUrl("http://h", "HOST"));
  EXPECT_EQ("", parseUrl("http://h", "PATH"));
  EXPECT_EQ("h", parseUrl("http://h?q", "HOST"));
  EXPECT_EQ("q", parseUrl("http://h?q", "QUERY"));
  EXPECT_EQ("?q", parseUrl("http://h?q", "FILE"));
  EXPECT_EQ("", parseUrl("http://h#f", "PATH"));
  EXPECT_EQ("f", parseUrl("http://h#f", "REF"));
  EXPECT_EQ("//p", parseUrl("http:////p", "PATH"));
  EXPECT_EQ("/p", parseUrl("///p", "PATH"));
  EXPECT_EQ(std::nullopt, parseUrl("///p", "AUTHORITY"));
  EXPECT_EQ("h", parseUrl("//h", "HOST"));
}

// Pins the three-argument form: the part must be exactly QUERY and the
// value is extracted with the (&|^)key=([^&]*) regex over the raw query.
TEST_F(ParseUrlTest, queryKeyExtraction) {
  EXPECT_EQ("1", parseUrlQuery("http://h/p?a=1&&b=2", "a"));
  EXPECT_EQ("2", parseUrlQuery("http://h/p?a=1&&b=2", "b"));
  // An empty key is not special-cased: the regex becomes (&|^)=([^&]*).
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?a=1&&b=2", ""));
  EXPECT_EQ("", parseUrlQuery("http://h/p?=&b=2", ""));
  // A key present with an empty value yields an empty string, and a key
  // without '=' yields null.
  EXPECT_EQ("", parseUrlQuery("http://h/p?k=", "k"));
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?k", "k"));
  // The first matching occurrence wins.
  EXPECT_EQ("2", parseUrlQuery("http://h/p?ak=1&k=2", "k"));
  EXPECT_EQ("1", parseUrlQuery("http://h/p?a=1#f", "a"));
  // Key matching is case sensitive and must not match a longer name.
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?a=1", "A"));
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?ab=1", "a"));
  // Real-world shapes from the mismatch data.
  EXPECT_EQ(
      "10000987",
      parseUrlQuery(
          "https://www.example.com/x.html?isLimitPoi=false&poiId=10000987&poi=10000987",
          "poi"));
  EXPECT_EQ(
      "10000987",
      parseUrlQuery(
          "https://www.example.com/x.html?poi=10000987&poiId=10000987", "poi"));
  // A missing query yields null, and so does a missing key.
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p", "a"));
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?b=2", "a"));

  // A three-argument call with a part other than QUERY returns null.
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, 'HOST', c1)",
          std::optional<std::string>("http://h/p?a=1"),
          std::optional<std::string>("a")));
  EXPECT_EQ(
      "1",
      evaluateOnce<std::string>(
          "parse_url(c0, 'QUERY', 'a')",
          std::optional<std::string>("http://h/p?a=1")));
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, 'QUERY', 'b')",
          std::optional<std::string>("http://h/p?a=1")));
}

// Pins the non-constant key path: a per-row key column bypasses
// initialize()'s constant-key compilation and goes through the bounded
// regex cache in call().
TEST_F(ParseUrlTest, nonConstantKey) {
  const auto run = [&](std::vector<std::optional<StringView>> urls,
                       std::vector<std::optional<StringView>> keys) {
    return evaluate(
        "parse_url(c0, 'QUERY', c1)",
        makeRowVector(
            {makeNullableFlatVector<StringView>(std::move(urls)),
             makeNullableFlatVector<StringView>(std::move(keys))}));
  };

  // Distinct keys per row each extract their own parameter.
  assertEqualVectors(
      makeNullableFlatVector<StringView>({"1", "2", std::nullopt}),
      run({"http://h/p?a=1", "http://h/p?b=2", "http://h/p?c=3"},
          {"a", "b", "d"}));

  // A null key yields a null result.
  assertEqualVectors(
      makeNullableFlatVector<StringView>({std::nullopt}),
      run({"http://h/p?a=1"}, {std::nullopt}));

  // An invalid key fails the query with the raw regex error, like the
  // regexp functions; a constant invalid key fails in initialize() with
  // 'invalid key'. Spark fails both forms identically with
  // PatternSyntaxException, so silently returning null here would diverge.
  VELOX_ASSERT_THROW(
      run({"http://h/p?a=1"}, {"a["}), "invalid regular expression:");

  // A constant invalid key, pinned for symmetry with the case above.
  VELOX_ASSERT_THROW(
      evaluateOnce<std::string>(
          "parse_url(c0, 'QUERY', 'a[')",
          std::optional<std::string>("http://h/p?a=1")),
      "invalid key: a[");

  // More than "expression.max_compiled_regexes" distinct keys fails the
  // query, matching how regexp_replace treats its pattern column.
  const auto maxCompiledRegexes =
      core::QueryConfig({}).exprMaxCompiledRegexes();
  const auto aboveMaxCompiledRegexes = maxCompiledRegexes + 5;
  std::vector<std::string> urlStrings(aboveMaxCompiledRegexes);
  std::vector<std::string> keyStrings(aboveMaxCompiledRegexes);
  for (auto i = 0; i < aboveMaxCompiledRegexes; ++i) {
    urlStrings[i] = fmt::format("http://h/p?k{}=v{}", i, i);
    keyStrings[i] = fmt::format("k{}", i);
  }
  VELOX_ASSERT_THROW(
      run({urlStrings.begin(), urlStrings.end()},
          {keyStrings.begin(), keyStrings.end()}),
      "Max number of regex reached");
}

// Pins null propagation: any null argument yields a null result, including
// the key of the three-argument form.
TEST_F(ParseUrlTest, nullArguments) {
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, 'HOST')", std::optional<std::string>(std::nullopt)));
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, c1)",
          std::optional<std::string>("http://h/p"),
          std::optional<std::string>(std::nullopt)));
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, 'QUERY', c1)",
          std::optional<std::string>("http://h/p?a=1"),
          std::optional<std::string>(std::nullopt)));
}

// Pins the '#'-before-'?' split: a '?' inside the fragment belongs to the
// fragment and never introduces a query.
TEST_F(ParseUrlTest, questionMarkInFragment) {
  const auto url = "http://h/p#f?g";
  EXPECT_EQ(std::nullopt, parseUrl(url, "QUERY"));
  EXPECT_EQ("f?g", parseUrl(url, "REF"));
  EXPECT_EQ("/p", parseUrl(url, "FILE"));
  EXPECT_EQ("/p", parseUrl(url, "PATH"));
  EXPECT_EQ("h", parseUrl(url, "HOST"));
  // The '?' inside the fragment also stays out of the FILE, and a query
  // key finds nothing.
  EXPECT_EQ(
      std::nullopt,
      evaluateOnce<std::string>(
          "parse_url(c0, 'QUERY', 'f')", std::optional<std::string>(url)));
}

// Pins that the key is a regex fragment, not a literal: no escaping.
TEST_F(ParseUrlTest, regexMetacharacterKey) {
  // '.' matches any character, so 'a.b' hits 'aXb=1'.
  EXPECT_EQ("1", parseUrlQuery("http://h/p?aXb=1", "a.b"));
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?ab=1", "a.b"));
  // The '=' after the key is a literal, so 'b*' matching empty still
  // leaves no '=' to match: 'ab*' does not hit a bare 'a'.
  EXPECT_EQ(std::nullopt, parseUrlQuery("http://h/p?a", "ab*"));
}

// Pins IPv6 literal shapes beyond '::1': the unspecified address,
// embedded IPv4, scope ids, full-width groups, and the malformed forms.
TEST_F(ParseUrlTest, ipv6LiteralShapes) {
  const auto host = [&](const std::string& url) {
    return evaluateOnce<std::string>(
        "parse_url(c0, 'HOST')", std::optional<std::string>(url));
  };
  const auto authority = [&](const std::string& url) {
    return evaluateOnce<std::string>(
        "parse_url(c0, 'AUTHORITY')", std::optional<std::string>(url));
  };

  // Legal shapes.
  EXPECT_EQ("[::]", host("http://[::]/p"));
  EXPECT_EQ("[::ffff:1.2.3.4]", host("http://[::ffff:1.2.3.4]/p"));
  EXPECT_EQ("[1:2:3:4:5:6:7:8]", host("http://[1:2:3:4:5:6:7:8]/p"));
  // A scope id is alphanumeric only and must be non-empty; '%' is a mask
  // member in the authority, not an escape.
  EXPECT_EQ("[fe80::1%eth0]", host("http://[fe80::1%eth0]/p"));
  EXPECT_EQ("[fe80::1%eth0]:80", authority("http://[fe80::1%eth0]:80/p"));

  // Malformed shapes yield a null host. Unlike a non-IPv6 authority, a
  // malformed IPv6 literal fails the whole authority, so AUTHORITY is
  // null too.
  EXPECT_EQ(std::nullopt, host("http://[fe80::1%]/p"));
  EXPECT_EQ(std::nullopt, host("http://[fe80::1%e!h0]/p"));
  EXPECT_EQ(std::nullopt, host("http://[1:2:3:4:5:6:7:8:9]/p"));
  EXPECT_EQ(std::nullopt, host("http://[12345::]/p"));
  EXPECT_EQ(std::nullopt, host("http://[1::2::3]/p"));
  EXPECT_EQ(std::nullopt, host("http://[:1]/p"));
  EXPECT_EQ(std::nullopt, authority("http://[1::2::3]/p"));
}

// Pins that the host keeps its original casing (java.net.URI does not
// lowercase) and that userinfo escapes pass through undecoded.
TEST_F(ParseUrlTest, hostCaseAndUserInfoEscapes) {
  EXPECT_EQ("HoSt", parseUrl("HTTP://HoSt/p", "HOST"));
  EXPECT_EQ("HoSt", parseUrl("http://HoSt/p", "HOST"));
  EXPECT_EQ("us%65r", parseUrl("http://us%65r@h/", "USERINFO"));
  EXPECT_EQ("h", parseUrl("http://us%65r@h/", "HOST"));
}

// Exercises parse_url with components long enough to span AVX2 chunks and
// a stopper at index 40, inside the second chunk (bytes 32..63). All
// expectations verified against Spark 3.5.1.
TEST_F(ParseUrlTest, parseUrlLongComponents) {
  const auto repeat = [](int count, char c) { return std::string(count, c); };
  const auto repeatStr = [](std::string_view unit, int count) {
    std::string out;
    for (int i = 0; i < count; ++i) {
      out += unit;
    }
    return out;
  };

  // A 69-character valid hostname crosses two chunks with no stopper.
  const auto longHost = repeatStr("aaaa.", 13) + "aaaa";
  const auto longHostUrl = "http://" + longHost + "/p";
  EXPECT_EQ(longHost, parseUrl(longHostUrl, "HOST"));
  EXPECT_EQ(longHost, parseUrl(longHostUrl, "AUTHORITY"));
  EXPECT_EQ("http", parseUrl(longHostUrl, "PROTOCOL"));

  // A space at index 40 of the host fails every authority form, so the
  // whole URL is invalid and every part is null.
  const auto spaceInHostUrl =
      "http://" + repeat(40, 'a') + " " + repeat(28, 'b') + "/p";
  EXPECT_EQ(std::nullopt, parseUrl(spaceInHostUrl, "HOST"));
  EXPECT_EQ(std::nullopt, parseUrl(spaceInHostUrl, "AUTHORITY"));
  EXPECT_EQ(std::nullopt, parseUrl(spaceInHostUrl, "PATH"));

  // A malformed escape pair at index 40 invalidates the path.
  const auto badEscapePathUrl =
      "http://h/" + repeat(40, 'p') + "%x" + repeat(27, 'p');
  EXPECT_EQ(std::nullopt, parseUrl(badEscapePathUrl, "PATH"));

  // A CJK character at index 40 of the path and the query is accepted
  // and preserved byte-for-byte.
  const auto cjkPathUrl =
      "http://h/" + repeat(40, 'p') + "中" + repeat(27, 'p');
  EXPECT_EQ(
      "/" + repeat(40, 'p') + "中" + repeat(27, 'p'),
      parseUrl(cjkPathUrl, "PATH"));
  const auto cjkQueryUrl = "http://h/p?" + repeat(40, 'k') + "=美&x=1";
  EXPECT_EQ(repeat(40, 'k') + "=美&x=1", parseUrl(cjkQueryUrl, "QUERY"));
}

} // namespace
} // namespace facebook::velox::functions::sparksql::test
