# Invoked as: cmake -DTHRIFT_SRC=<thrift extract root> -P velox_thrift_mutex_patch.cmake
# Fixes GCC 15+ / libstdc++: int64_t used in Mutex.h without <cstdint>.
if(NOT DEFINED THRIFT_SRC)
  message(FATAL_ERROR "THRIFT_SRC not set")
endif()
set(_mutex "${THRIFT_SRC}/lib/cpp/src/thrift/concurrency/Mutex.h")
if(NOT EXISTS "${_mutex}")
  message(FATAL_ERROR "Thrift Mutex.h not found: ${_mutex}")
endif()
file(READ "${_mutex}" _buf)
string(FIND "${_buf}" "#include <cstdint>" _pos)
if(NOT _pos EQUAL -1)
  return()
endif()
string(REPLACE "#include <memory>"
       "#include <memory>\n#include <cstdint>" _out "${_buf}")
if(_out STREQUAL _buf)
  message(FATAL_ERROR "velox_thrift_mutex_patch: expected #include <memory> in Mutex.h")
endif()
file(WRITE "${_mutex}" "${_out}")
