name: format-check
on:
  workflow_dispatch:
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image : ghcr.io/facebookincubator/velox-dev:check-avx
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check formatting
        run: |
          if ! make format-check; then
            make format-fix
            echo -e "\n==== Apply using:"
            echo "patch -p1 \<<EOF"
            git --no-pager diff
            echo "EOF"
            false
          fi