name: linux-build-options
on:
    workflow_dispatch:
    pull_request:

jobs:
  linux-build-options:
    runs-on: 32-core
    container:
      image : ghcr.io/facebookincubator/velox-dev:circleci-avx
    env:
      CC:  /opt/rh/gcc-toolset-9/root/bin/gcc
      CXX: /opt/rh/gcc-toolset-9/root/bin/g++
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
      - uses: "./.github/actions/setup-environment"
      - name: Build Velox Minimal
        run: |
          make min_debug NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=16
      - name: Build Velox Without Testing
        run: |
          make clean
          make debug EXTRA_CMAKE_FLAGS="-DVELOX_BUILD_TESTING=OFF" NUM_THREADS=16 MAX_HIGH_MEM_JOBS=8 MAX_LINK_JOBS=16
