# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Linux Build using Clang

on:
  pull_request:
    paths:
      - "velox/**"
      - "!velox/docs/**"
      - "CMakeLists.txt"
      - "CMake/**"
      - "third_party/**"
      - "scripts/setup-ubuntu.sh"
      - "scripts/setup-common.sh"
      - "scripts/setup-versions.sh"
      - "scripts/setup-helper-functions.sh"
      - ".github/workflows/scheduled.yml"
      - "setup.py"

  push:
    branches:
      - "presto-0.293-clp-connector"
    paths:
      - "velox/**"
      - "!velox/docs/**"
      - "CMakeLists.txt"
      - "CMake/**"
      - "third_party/**"
      - "scripts/setup-ubuntu.sh"
      - "scripts/setup-common.sh"
      - "scripts/setup-versions.sh"
      - "scripts/setup-helper-functions.sh"
      - ".github/workflows/scheduled.yml"

  schedule:
    # Run at 6am UTC to avoid interrupting late night work in Toronto.
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha  }}
  cancel-in-progress: ${{github.ref != 'refs/heads/presto-0.293-clp-connector'}}

jobs:
  linux-clang:
    if: ${{ github.event_name == 'schedule' }}
    name: Build with Clang
    uses: ./.github/workflows/linux-build-base.yml
    with:
      use-clang: true
